This commit was manufactured by cvs2svn to create tag 'R-1-6-2'.

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,11 +4,11 @@
 
 # @configure_input@
 
-revision='$Revision: 1.106 $'
+revision='$Revision: 1.92.2.1 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
-Copyright (C) 2000-2003 The R Core Development Team.
+Copyright (C) 2000-2002 The R Core Development Team.
 This is free software; see the GNU General Public Licence version 2
 or later for copying conditions.  There is NO warranty."
 
@@ -26,8 +26,7 @@ Options:
   -h, --help		print short help message and exit
   -v, --version		print version info and exit
       --configure-args=ARGS
-                        set arguments for the package's configure script
-			(if any)
+                        set args for package's configure script (if any)
       --configure-vars=VARS
                         set variables for the configure script (if any)
   -c, --clean		remove all files created during installation
@@ -51,15 +50,6 @@ Report bugs to <r-bugs@r-project.org>."
 ## According to the R Coding Standards (see R-exts), Perl can be assumed
 ## for *source*, but not for *binary* installations.
 ## </NOTE>
-
-## <FIXME>
-## This uses
-##   mkdir -p
-##   basename
-## which are not portable.
-## We could fix this using suitable shell replacements, but we should
-## really redo as much as we can using R code.
-## </FIXME>
 
 umask 022
 
@@ -105,7 +95,7 @@ stars="*"
 get_packages () {
   ## get the full path names to all packages contained in $1.
   ## NOTE: modifies pkgs!
-  if grep "^Contains:" "${1}/DESCRIPTION" >/dev/null; then
+  if grep -s "^Contains:" "${1}/DESCRIPTION"; then
     bundlepkg=`get_dcf_field Contains "${1}/DESCRIPTION"`
     for p in ${bundlepkg}; do
       pkgs="${pkgs} \"`cd "${1}/${p}" && ${GETWD}`\""
@@ -119,15 +109,11 @@ get_packages () {
   fi
 }
 
-### 
-### Setup and command line processing.
-
-if test -n "${R_LIBS}"; then
-  lib=`echo "${R_LIBS}" | cut -f1 -d:`
-else
-  lib="${R_HOME}/library"
-fi
-
+## <NOTE>
+## Using ${VAR:-value} is not portable shell programming.
+## But we cannot simply use ${VAR-value}: see the usage info.
+lib=`echo ${R_LIBS:-"${R_HOME}/library"} | cut -f1 -d:`
+## </NOTE>
 pkgs=
 clean=false
 debug=false
@@ -253,259 +239,6 @@ elif ${debug}; then
   build_help_opts="--debug ${build_help_opts}"
 fi
 
-### 
-### Install a *binary* package from the current directory. 
-
-do_install_binary () {
-  pkg="${1}"
-  message "Installing *binary* package '${pkg}' ..."
-  cp -r . "${lib}/${pkg}"
-}
-
-### 
-### Install a *source* package from the current directory.
-
-do_install_source () {
-  pkg="${1}"
-  message "Installing *source* package '${pkg}' ..."
-  stars="**"
-
-  ## Make the destination directories available to the developer's
-  ## installation scripts (e.g. configure, etc.)
-  R_PACKAGE_DIR="${lib}/${pkg}"
-  R_LIBRARY_DIR="${lib}"
-  R_PACKAGE_NAME="${pkg}"
-  export R_LIBRARY_DIR
-  export R_PACKAGE_DIR
-  export R_PACKAGE_NAME
-
-  if ${use_configure} && test -x ./configure ; then
-    eval ${configure_vars} ./configure ${configure_args}
-    if test ${?} -ne 0; then
-      echo "ERROR: configuration failed for package '${pkg}'"
-      exit 4
-    fi
-  fi
-
-  if test -d src; then
-    message "libs"
-    if ${debug}; then set -x; fi
-    mkdir -p "${lib}/${pkg}/libs"
-    if test -f src/Makefile; then
-      cd src;
-      makefiles="-f \"${R_HOME}\"/share/make/shlib.mk -f Makefile"
-      if test -r Makevars; then
-	makefiles="-f Makevars ${makefiles}"
-      fi
-      eval ${MAKE} ${makefiles} \
-	&& cp *@SHLIB_EXT@ "${lib}/${pkg}/libs" \
-        || error=true; \
-      if ${clean}; then
-	${MAKE} clean
-      fi
-      cd ..
-    else
-      cd src;
-      srcs=`ls *.[cfC] *.cc *.cpp 2>/dev/null`
-      if test -n "${srcs}"; then
-	sh "${R_HOME}/bin/SHLIB" -o "${pkg}@SHLIB_EXT@" ${srcs} \
-          && cp *@SHLIB_EXT@ "${lib}/${pkg}/libs" \
-	  || error=true; \
-	if ${clean}; then
-	  rm -rf .libs _libs
-	  rm -f *.o *@SHLIB_EXT@
-	fi
-      else
-	echo "WARNING: no source files found"
-      fi
-      cd ..
-    fi
-    if ${error}; then
-      echo "ERROR: compilation failed for package '${pkg}'"
-      exit 5
-    fi
-    if ${debug}; then set +x; fi
-  fi
-
-  if test -d R; then
-    message "R"
-    Rfiles=`LC_COLLATE=C ls R/*.[RSqrs] R/${R_OSTYPE}/*.[RSqrs] 2>/dev/null`
-    if test -n "${Rfiles}"; then
-      mkdir -p "${lib}/${pkg}/R"
-	rm -f "${lib}/${pkg}/R/"*
-	echo ".packageName <- \"${pkg}\"" > "${lib}/${pkg}/R/${pkg}"
-      cat ${Rfiles} >> "${lib}/${pkg}/R/${pkg}"
-    fi
-  fi
-
-  if test -d data; then
-    message "data"
-    mkdir -p "${lib}/${pkg}/data"
-    rm -f "${lib}/${pkg}/data/"*
-    cp data/* "${lib}/${pkg}/data" 2>/dev/null
-    chmod 644 "${lib}/${pkg}/data/"*
-    if test -n "${use_zip_data}" \
-        -a -n "${R_UNZIPCMD}" \
-        -a -n "${R_ZIPCMD}"; then
-      (cd "${lib}/${pkg}/data";
-        find . -type f -print > filelist
-        ${R_ZIPCMD} -m Rdata * -x filelist 00Index)
-    fi
-  fi
-
-  if test -d demo; then
-    message "demo"
-    mkdir -p "${lib}/${pkg}/demo"
-    rm -f "${lib}/${pkg}/demo/"*
-    cp demo/* "${lib}/${pkg}/demo" 2>/dev/null
-    chmod 644 "${lib}/${pkg}/demo/"*
-  fi
-
-  if test -d exec; then
-    message "exec"
-    mkdir -p "${lib}/${pkg}/exec"
-    rm -f "${lib}/${pkg}/exec/"*
-    cp exec/* "${lib}/${pkg}/exec" 2>/dev/null
-    chmod 755 "${lib}/${pkg}/exec/"*
-  fi
-
-  if test -d inst; then
-    message "inst"
-    ## <FIXME>
-    ## When installing from a source directory under CVS control, we
-    ## should really exclude the CVS subdirs.  (In fact, we should also
-    ## exclude everything in @file{.Rbuildignore}, but that's another
-    ## story ...)
-    cp -r inst/* "${lib}/${pkg}"
-  fi
-
-  case ${save} in
-    CHECK)
-      if test -r install.R; then
-	R_SAVE_IMAGE=true;
-      else
-	R_SAVE_IMAGE=false;
-      fi
-      ;;
-    *)
-      R_SAVE_IMAGE=${save} ;;
-  esac
-  export R_SAVE_IMAGE
-
-  if ${R_SAVE_IMAGE}; then
-    message "save image"
-    ## <NOTE>
-    ## We want R to run as quietly as possible when creating the save
-    ## image.  But this is tricky: sending options(echo=FALSE) to R via
-    ## stdin (as opposed to writing to a file and reading from it)
-    ## echoes what we sent before shutting up R, which is not what we
-    ## want.  Option '--slave' gets around this but also turns off
-    ## saving ... hence we call R with '--slave --save'.  Argh.
-    save_image_defaults="list(compress=TRUE, safe=FALSE)"
-    (echo "options(save.image.defaults=${save_image_defaults})"; \
-      if test -s R_PROFILE.R; then cat R_PROFILE.R; fi; \
-      echo "invisible(.libPaths(c(\"${lib}\", .libPaths())))"; \
-      cat "${lib}/${pkg}/R/${pkg}") | \
-	  ${R_EXE} --slave --save ${save_args}
-    ## </NOTE>
-    if test ${?} -ne 0; then
-      echo "ERROR: execution of package source for '${pkg}' failed"
-	exit 1
-    fi
-    mv .RData "${lib}/${pkg}/R/all.rda"
-    mv "${lib}/${pkg}/R/${pkg}" "${lib}/${pkg}/R/${pkg}.R"
-    cat "${R_HOME}/share/R/firstlib.R" > "${lib}/${pkg}/R/${pkg}"
-    ## If install.R is non-empty, arrange to evaluate the R code it
-    ## contains after the package source (maybe for some kind of
-    ## cleanup).
-    if test -s install.R; then
-      cat install.R >> "${lib}/${pkg}/R/${pkg}"
-    fi
-  fi
-
-  for f in COPYING; do
-    if test -f "${f}"; then cp "${f}" "${lib}/${pkg}"; fi
-  done
-  ## Copy DESCRIPTION file, stamp with build information, and remove
-  ## blank lines.  (Need to add an empty line to deal with missing
-  ## trailing newlines at EOF.)
-  ## As from 1.7.0, packages without compiled code are not marked
-  ## as being from any platform.
-  if test -f DESCRIPTION; then
-    ## <FIXME>
-    ## What if there is no DESCRIPTION file?
-    ## Shouldn't we fail right away then?
-    ## </FIXME>
-    (echo "library(tools)"; \
-      echo ".installPackageDescription(\".\", \"${lib}/${pkg}\")") | \
-	${R_EXE} --vanilla >/dev/null
-  fi
-
-  if test -d man; then
-    message "help"
-    ## Install man sources ...
-    Rdfiles=`ls man/*.[Rr]d man/${R_OSTYPE}/*.[Rr]d 2>/dev/null`
-    if test -n "${Rdfiles}"; then
-      mkdir -p "${lib}/${pkg}/man"
-      rm -f "${lib}/${pkg}/man/"*
-      for f in ${Rdfiles}; do cat "${f}"; echo '\eof'; done \
-        > "${lib}/${pkg}/man/${pkg}.Rd"
-      chmod 644 "${lib}/${pkg}/man/${pkg}.Rd"
-    fi
-    ## Maybe build preformatted help pages ...
-    if ${build_help}; then
-      if ${NO_PERL5}; then
-	echo "${NO_PERL5_MSG}"
-      else
-	if ${debug}; then
-	  echo "DEBUG: build-help ${BUILD_HELP_OPTS} ../${pkg} ${lib}"
-	fi
-	${R_CMD} perl "${R_HOME}/share/perl/build-help.pl" \
-	  ${build_help_opts} "../${pkg}" "${lib}"
-	if test ${?} -ne 0; then
-	  echo "ERROR: building help failed for package '${pkg}'"
-	  exit 6
-        fi
-	if test "${lib}" = `cd "${R_HOME}/library" && ${GETWD}`; then
-	  ${R_CMD} perl "${R_HOME}/share/perl/build-help.pl" --htmllists
-	fi
-      fi
-      if test -n "${use_zip_help}" \
-	  -a -n "${R_UNZIPCMD}" \
-	  -a -n "${R_ZIPCMD}"; then
-	(cd "${lib}/${pkg}"
-	  if test -d R-ex; then
-	    (cd R-ex; ${R_ZIPCMD} -m Rex *.R)
-	  fi
-          ## NOT YET:
-          ## if test -d latex; then
-          ##   (cd latex; ${R_ZIPCMD} -m Rhelp *.tex)
-          ## fi
-	  if test -d help; then
-	    (cd help; ${R_ZIPCMD} -m Rhelp * -x AnIndex);
-	  fi)
-      fi
-    fi
-  else
-    echo "No man pages found in package '${pkg}'"
-  fi
-
-  (echo "library(tools)"; \
-    echo ".installPackageIndices(\".\", \"${lib}/${pkg}\")") | \
-      ${R_EXE} --vanilla >/dev/null
-
-  if ${clean}; then
-    if test -x ./cleanup ; then
-      ./cleanup
-    fi
-  fi
-
-  stars="*"
-}
-
-### 
-### Install a package.
-
 do_install () {
   cd "${1}"
   pkg=`basename "${1}"`
@@ -516,7 +249,7 @@ do_install () {
     depends=`echo "${depends}" | sed 's/.*R *(\([^)]*\)).*/\1/;s/=/= /'`
     dep_operator=`set - ${depends}; echo ${1}`
     dep_version=`set - ${depends}; echo ${2}`
-    ## Currently, only operators '<=' and '>=' are supported.  Hence we
+    ## Currently, only operators `<=' and `>=' are supported.  Hence we
     ## check this, and also whether we found a version string.
     if (test "${dep_operator}" = "<=" \
 	|| test "${dep_operator}" = ">=") \
@@ -563,39 +296,258 @@ do_install () {
 
   if ${is_source_package}; then
     ## This is a source package ... hopefully.
-    do_install_source "${pkg}"
+    message "Installing *source* package '${pkg}' ..."
+    stars="**"
+
+    ## Make the destination directories available to the developer's
+    ## installation scripts (e.g. configure, etc.)
+    R_PACKAGE_DIR="${lib}/${pkg}"
+    R_LIBRARY_DIR="${lib}"
+    R_PACKAGE_NAME="${pkg}"
+    export R_LIBRARY_DIR
+    export R_PACKAGE_DIR
+    export R_PACKAGE_NAME
+
+    if ${use_configure} && test -x ./configure ; then
+      eval ${configure_vars} ./configure ${configure_args}
+      if test ${?} -ne 0; then
+	echo "ERROR: configuration failed for package '${pkg}'"
+	exit 4
+      fi
+    fi
+
+    if test -d src; then
+      message "libs"
+      if ${debug}; then set -x; fi
+      ## <FIXME>
+      ## Is 'mkdir -p' portable?
+      mkdir -p "${lib}/${pkg}/libs"
+      ## </FIXME>
+      if test -f src/Makefile; then
+        cd src;
+        makefiles="-f \"${R_HOME}\"/share/make/shlib.mk -f Makefile"
+	if test -r Makevars; then
+	  makefiles="-f Makevars ${makefiles}"
+	fi
+	eval ${MAKE} ${makefiles} \
+	  && cp *@SHLIB_EXT@ "${lib}/${pkg}/libs" \
+	  || error=true; \
+	if ${clean}; then
+	  ${MAKE} clean
+	fi
+	cd ..
+      else
+        cd src;
+        srcs=`ls *.[cfC] *.cc *.cpp 2>/dev/null`
+	if test -n "${srcs}"; then
+	  sh "${R_HOME}/bin/SHLIB" -o "${pkg}@SHLIB_EXT@" ${srcs} \
+	    && cp *@SHLIB_EXT@ "${lib}/${pkg}/libs" \
+  	    || error=true; \
+	  if ${clean}; then
+	    rm -rf .libs _libs
+	    rm -f *.o *@SHLIB_EXT@
+	  fi
+	else
+	  echo "WARNING: no source files found"
+	fi
+	cd ..
+      fi
+      if ${error}; then
+	echo "ERROR: compilation failed for package '${pkg}'"
+	exit 5
+      fi
+      if ${debug}; then set +x; fi
+    fi
+
+    if test -d R; then
+      message "R"
+      Rsrcs=`LC_COLLATE=C ls R/*.[RSqrs] R/${R_OSTYPE}/*.[RSqrs] 2>/dev/null`
+      if test -n "${Rsrcs}"; then
+        mkdir -p "${lib}/${pkg}/R"
+	rm -f "${lib}/${pkg}/R/"*
+	echo ".packageName <- \"${pkg}\"" > "${lib}/${pkg}/R/${pkg}"
+        cat ${Rsrcs} >> "${lib}/${pkg}/R/${pkg}"
+      fi
+    fi
+
+    if test -d data; then
+      message "data"
+      mkdir -p "${lib}/${pkg}/data"
+      rm -f "${lib}/${pkg}/data/"*
+      cp data/* "${lib}/${pkg}/data" 2>/dev/null
+      chmod 644 "${lib}/${pkg}/data/"*
+      if test -n "${use_zip_data}" \
+          -a -n "${R_UNZIPCMD}" \
+          -a -n "${R_ZIPCMD}"; then
+        (cd "${lib}/${pkg}/data";
+          find . -type f -print > filelist
+          ${R_ZIPCMD} -m Rdata * -x filelist 00Index)
+      fi
+    fi
+
+    if test -d demo; then
+      message "demo"
+      mkdir -p "${lib}/${pkg}/demo"
+      rm -f "${lib}/${pkg}/demo/"*
+      cp demo/* "${lib}/${pkg}/demo" 2>/dev/null
+      chmod 644 "${lib}/${pkg}/demo/"*
+    fi
+
+    if test -d exec; then
+      message "exec"
+      mkdir -p "${lib}/${pkg}/exec"
+      rm -f "${lib}/${pkg}/exec/"*
+      cp exec/* "${lib}/${pkg}/exec" 2>/dev/null
+      chmod 755 "${lib}/${pkg}/exec/"*
+    fi
+
+    if test -d inst; then
+      message "inst"
+      cp -r inst/* "${lib}/${pkg}"
+    fi
+
+    case ${save} in
+      CHECK)
+	if test -r install.R; then
+	  R_SAVE_IMAGE=true;
+        else
+	  R_SAVE_IMAGE=false;
+        fi
+	;;
+      *)
+	R_SAVE_IMAGE=${save} ;;
+    esac
+    export R_SAVE_IMAGE
+
+    if ${R_SAVE_IMAGE}; then
+      message "save image"
+      ## <NOTE>
+      ## We want R to run as quietly as possible when creating the save
+      ## image.  But this is tricky: sending options(echo=FALSE) to R via
+      ## stdin (as opposed to writing to a file and reading from it)
+      ## echoes what we sent before shutting up R, which is not what we
+      ## want.  Option '--slave' gets around this but also turns off
+      ## saving ... hence we call R with '--slave --save'.  Argh.
+      save_image_defaults="list(compress=TRUE, safe=FALSE)"
+      (echo "options(save.image.defaults=${save_image_defaults})"; \
+        if test -s R_PROFILE.R; then cat R_PROFILE.R; fi; \
+        echo "invisible(.libPaths(c(\"${lib}\", .libPaths())))"; \
+        cat "${lib}/${pkg}/R/${pkg}") | \
+	  ${R_EXE} --slave --save ${save_args}
+      ## </NOTE>
+      if test ${?} -ne 0; then
+        echo "ERROR: execution of package source for '${pkg}' failed"
+	exit 1
+      fi
+      mv .RData "${lib}/${pkg}/R/all.rda"
+      mv "${lib}/${pkg}/R/${pkg}" "${lib}/${pkg}/R/${pkg}.R"
+      cat "${R_HOME}/share/R/firstlib.R" > "${lib}/${pkg}/R/${pkg}"
+      ## If install.R is non-empty, arrange to evaluate the R code it
+      ## contains after the package source (maybe for some kind of
+      ## cleanup).
+      if test -s install.R; then
+        cat install.R >> "${lib}/${pkg}/R/${pkg}"
+      fi
+    fi
+
+    for f in COPYING INDEX; do
+      if test -f "${f}"; then cp "${f}" "${lib}/${pkg}"; fi
+    done
+    title=`get_dcf_field Title DESCRIPTION`
+    if test "${title}"; then
+      ${R_CMD} perl "${R_HOME}/share/perl/maketitle.pl" DESCRIPTION \
+        > "${lib}/${pkg}/TITLE"
+    elif test -f TITLE; then
+      cp TITLE "${lib}/${pkg}"
+    fi
+    ## Copy DESCRIPTION file, stamp with build information, and remove
+    ## blank lines.  (Need to add an empty line to deal with missing
+    ## trailing newlines at EOF.)
+    if test -f DESCRIPTION; then
+      (cat DESCRIPTION; \
+        echo; \
+        echo "Built: R" ${R_VERSION}\;  ${R_PLATFORM}\;  `date`) \
+	  | sed '/^[	]*$/d;' \
+	> "${lib}/${pkg}/DESCRIPTION"
+    fi
+
+    if test -d man; then
+      message "help"
+      ## Install man sources ...
+      Rdfiles=`ls man/*.[Rr]d man/${R_OSTYPE}/*.[Rr]d 2>/dev/null`
+      if test -n "${Rdfiles}"; then
+	mkdir -p "${lib}/${pkg}/man"
+	rm -f "${lib}/${pkg}/man/"*
+	cat ${Rdfiles} > "${lib}/${pkg}/man/${pkg}.Rd"
+	chmod 644 "${lib}/${pkg}/man/${pkg}.Rd"
+      fi
+      ## Maybe build preformatted help pages ...
+      if ${build_help}; then
+	if ${NO_PERL5}; then
+	  echo "${NO_PERL5_MSG}"
+	else
+	  if ${debug}; then
+	    echo "DEBUG: build-help ${BUILD_HELP_OPTS} ../${pkg} ${lib}"
+	  fi
+	  ${R_CMD} perl "${R_HOME}/share/perl/build-help.pl" \
+	    ${build_help_opts} "../${pkg}" "${lib}"
+	  if test ${?} -ne 0; then
+	    echo "ERROR: building help failed for package '${pkg}'"
+	    exit 6
+	  fi
+	  ${R_CMD} perl "${R_HOME}/share/perl/Rd2contents.pl" \
+	    --os=${R_OSTYPE} "../${pkg}" > "${lib}/${pkg}/CONTENTS"
+	  if test "${lib}" = `cd "${R_HOME}/library" && ${GETWD}`; then
+	    ${R_CMD} perl "${R_HOME}/share/perl/build-help.pl" --htmllists
+	    cat "${R_HOME}"/library/*/CONTENTS \
+	      > "${R_HOME}"/doc/html/search/index.txt
+	  fi	
+	fi
+	if test -n "${use_zip_help}" \
+            -a -n "${R_UNZIPCMD}" \
+	    -a -n "${R_ZIPCMD}"; then
+	  cd "${lib}/${pkg}"
+	  if test -d R-ex; then
+	    (cd R-ex; ${R_ZIPCMD} -m Rex *.R)
+	  fi
+	  ## NOT YET:
+	  ## if test -d latex; then
+	  ##   (cd latex; ${R_ZIPCMD} -m Rhelp *.tex)
+	  ## fi
+	  if test -d help; then
+	    (cd help; ${R_ZIPCMD} -m Rhelp * -x AnIndex);
+	  fi
+        fi
+      fi
+    else
+      echo "No man pages found in package '${pkg}'"
+    fi
+
+    if ${clean}; then
+      if test -x ./cleanup ; then
+	./cleanup
+      fi
+    fi
+
+    stars="*"
   else  
     ## This is a binary package ... hopefully.
-    do_install_binary "${pkg}"
+    message "Installing *binary* package '${pkg}' ..."
+    cp -r . "${lib}/${pkg}"
   fi
 
   chmod -R a+r "${lib}/${pkg}"
-
-  ## <FIXME>
-  ## This is really something we should do once at the end, and not for
-  ## each package.  However, attempting to install a package can result
-  ## in a non-local exit without any cleanups ...
-  if test "${lib}" = `cd "${R_HOME}/library" && ${GETWD}`; then
-    cat "${R_HOME}"/library/*/CONTENTS \
-      > "${R_HOME}"/doc/html/search/index.txt
-  fi
-  ## </FIXME>
 
   message "DONE (${pkg})"
   echo
 }
 
-### 
-### Main loop and cleanup.
-
-startdir=`${GETWD}`
 eval "for pkg in ${pkgs}; do do_install \"\${pkg}\"; done"
 
 cp "${R_HOME}/doc/html/R.css" "${lib}"
 
-## Solaris will not remove any directory in the current path
-cd ${startdir}
 if test -d "${tmpdir}"; then
+  cd /
   rm -rf "${tmpdir}"
 fi
 
@@ -605,4 +557,3 @@ message "DONE (INSTALL)"
 ### mode: sh ***
 ### sh-indentation: 2 ***
 ### End: ***
-
