This commit was manufactured by cvs2svn to create tag 'R-1-7-1'.

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.120 $'
+revision='$Revision: 1.115.2.1 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
@@ -295,10 +295,11 @@ do_install_source () {
   fi  
   stars="**"
 
-  if test -f DESCRIPTION; then :; else
-    echo "ERROR: no DESCRIPTION file found"
-    exit 1
-  fi 
+  ## <FIXME>
+  ## Should really test for existence of DESCRIPTION file here, and
+  ## abort if there is none.  Once we do this, remove the existence test
+  ## when installing DESCRIPTION.
+  ## </FIXME>
 
   if ${use_configure} && test -x ./configure ; then
     eval ${configure_vars} ./configure ${configure_args}
@@ -395,7 +396,13 @@ do_install_source () {
 
   if test -d inst; then
     message "inst"
+    ## <FIXME>
+    ## When installing from a source directory under CVS control, we
+    ## should really exclude the CVS subdirs.  (In fact, we should also
+    ## exclude everything in @file{.Rbuildignore}, but that's another
+    ## story ...)
     cp -r inst/* "${R_PACKAGE_DIR}"
+    ## </FIXME>
   fi
 
   case ${save} in
@@ -428,7 +435,7 @@ do_install_source () {
     (echo "options(save.image.defaults=${save_image_defaults})"; \
       if test -s R_PROFILE.R; then cat R_PROFILE.R; fi; \
       echo "invisible(.libPaths(c(\"${lib}\", .libPaths())))"; \
-      cat "${R_PACKAGE_DIR}/R/${R_PACKAGE_NAME}") | \
+      cat "${R_PACKAGE_DIR}/R/${pkg}") | \
 	  ${R_EXE} --slave --save ${save_args}
     ## </NOTE>
     if test ${?} -ne 0; then
@@ -436,13 +443,31 @@ do_install_source () {
       exit 1
     fi
     mv .RData "${R_PACKAGE_DIR}/R/all.rda"
-    mv "${R_PACKAGE_DIR}/R/${R_PACKAGE_NAME}" "${R_PACKAGE_DIR}/R/${pkg}.R"
-    cat "${R_HOME}/share/R/firstlib.R" > "${R_PACKAGE_DIR}/R/${R_PACKAGE_NAME}"
+    mv "${R_PACKAGE_DIR}/R/${pkg}" "${R_PACKAGE_DIR}/R/${pkg}.R"
+    cat "${R_HOME}/share/R/firstlib.R" > "${R_PACKAGE_DIR}/R/${pkg}"
     ## If install.R is non-empty, arrange to evaluate the R code it
     ## contains after the package source (maybe for some kind of
     ## cleanup).
     if test -s install.R; then
-      cat install.R >> "${R_PACKAGE_DIR}/R/${R_PACKAGE_NAME}"
+      cat install.R >> "${R_PACKAGE_DIR}/R/${pkg}"
+    fi
+  fi
+
+  ## Copy DESCRIPTION file, stamp with build information, and remove
+  ## blank lines.  (Need to add an empty line to deal with missing
+  ## trailing newlines at EOF.)
+  ## As from 1.7.0, packages without compiled code are not marked
+  ## as being from any platform.
+  if test -f DESCRIPTION; then
+    ## <FIXME>
+    ## What if there is no DESCRIPTION file?
+    ## Shouldn't we fail right away then?
+    ## </FIXME>
+    echo ".installPackageDescription(\".\", \"${R_PACKAGE_DIR}\")" | \
+      R_DEFAULT_PACKAGES=tools ${R_EXE} --vanilla >/dev/null 2>&1
+    if test ${?} -ne 0; then
+      echo "ERROR: installing package DESCRIPTION failed"
+      exit 1
     fi
   fi
 
@@ -495,33 +520,12 @@ do_install_source () {
     echo "No man pages found in package '${pkg}'"
   fi
 
-  ## Copy DESCRIPTION file, stamp with build information, and remove
-  ## blank lines.  (Need to add an empty line to deal with missing
-  ## trailing newlines at EOF.)
-  ## As from 1.7.0, packages without compiled code are not marked
-  ## as being from any platform.
-  echo ".installPackageDescription(\".\", \"${R_PACKAGE_DIR}\")" | \
-    R_DEFAULT_PACKAGES=tools ${R_EXE} --vanilla >/dev/null
-  if test ${?} -ne 0; then
-    echo "ERROR: installing package DESCRIPTION failed"
-    exit 1
-  fi
-
   echo ".installPackageIndices(\".\", \"${R_PACKAGE_DIR}\")" | \
-    R_DEFAULT_PACKAGES=tools ${R_EXE} --vanilla >/dev/null
+    R_DEFAULT_PACKAGES=tools ${R_EXE} --vanilla >/dev/null 2>&1
   if test ${?} -ne 0; then
     echo "ERROR: installing package indices failed"
     exit 1
   fi
-
-  ## <FIXME>
-  ## Remove stuff we should not have installed in the first place.
-  ## When installing from a source directory under CVS control, we
-  ## should really exclude the CVS subdirs.  (In fact, we should also
-  ## exclude everything in @file{.Rbuildignore}, but that's another
-  ## story ...)
-  find "${R_PACKAGE_DIR}" -name CVS -exec rm -rf \{\} \; 2>/dev/null
-  ## </FIXME>
 
   if ${clean}; then
     if test -x ./cleanup ; then
