Tag version 2.11.1

diff --git a/src/scripts/Rd2dvi b/src/scripts/Rd2dvi
--- a/src/scripts/Rd2dvi
+++ b/src/scripts/Rd2dvi
@@ -9,7 +9,7 @@ revision='$Rev$'
 version=`set - ${revision}; echo ${2}`
 version="Rd2dvi: ${R_VERSION} (r${version})
 
-Copyright (C) 2000-2010 The R Core Development Team.
+Copyright (C) 2000-2009 The R Core Development Team.
 This is free software; see the GNU General Public License version 2
 or later for copying conditions.  There is NO warranty."
 
@@ -42,6 +42,7 @@ Options:
   -o, --output=FILE	write output to FILE
       --pdf		generate PDF output
       --title=NAME	use NAME as the title of the document
+  -V, --verbose		report on what is done
       --no-index	don't index output
       --no-description	don't typeset the description of a package
       --internals	typeset 'internal' documentation (usually skipped)
@@ -65,6 +66,7 @@ debug=false
 only_meta=false
 out_ext="dvi"
 output=""
+verbose=false
 enc=unknown
 outenc=latin1
 index=true
@@ -110,7 +112,8 @@ while test -n "${1}"; do
 	    preview=false
 	fi
       fi
-      export R_RD4DVI=${R_RD4PDF-"times,hyper"}
+      R_RD4DVI=${R_RD4PDF-"times,hyper"}
+      R_LATEXCMD="${R_PDFLATEXCMD}"
       ;;
     --title=*)
       title=`echo "${1}" | ${SED} -e 's/[^=]*=//'` ;;
@@ -134,6 +137,8 @@ while test -n "${1}"; do
       outenc=`echo "${1}" | ${SED} -e 's/[^=]*=//'` ;;
     --build-dir=*)
       build_dir=`echo "${1}" | ${SED} -e 's/[^=]*=//'` ;;
+    -V|--verbose)
+      verbose=${echo} ;;
     --no-index)
       index=false ;;
     --no-description)
@@ -167,13 +172,6 @@ if test -d "${1}"; then
     echo "Hmm ... looks like a package from the R distribution"
     dir=${1}
     test -z "${output}" && output="`basename ${1}`.${out_ext}"
-    if ${index}; then
-      this=`basename ${1}`
-      if test ${this} = "base"; then
-        index=false
-        echo "_not_ indexing 'base' package"
-      fi
-    fi
   else
     if test -d ${1}/man; then
       dir=${1}/man
@@ -208,19 +206,75 @@ echo "tools:::.Rd2dvi(\"${1}\",  \"${build_dir}/Rd2.tex\", \
 \"$enc\", \"$outenc\", \"${dir-$@}\", \"OSdir\", \"$internals\", \"$index\")" \
   | LC_ALL=C ${R_HOME}/bin/R --slave --vanilla || exit 11
 
+## <FIXME>
+## Need to do something smarter about the exit status in batch mode.
+status=0
+## <FIXME>
+
+
+R_TEXOPTS=
+if test "${R_OSTYPE}" = "windows"; then
+  miktex=`latex --version | grep ^MiKTeX | wc -l`
+  if test "${miktex}" = "1"; then
+    R_TEXOPTS=--include-directory=${R_HOME}/share/texmf
+  fi
+fi
+
 echo "Creating ${out_ext} output from LaTeX ..."
 cd ${build_dir}
-
-status=0
-echo "tools::texi2dvi('Rd2.tex', pdf=(\"${out_ext}\" == \"pdf\"), \
-    quiet=FALSE, index=(\"${index}\" != \"false\"))" | \
-   LC_ALL=C ${R_HOME}/bin/R --slave --vanilla || status=1
-if test $status -gt 0; then
-  echo "Error in running tools::texi2dvi"
+if test "${out_ext}" = pdf; then
+  ${R_PDFLATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+  if test $status -gt 0; then
+    echo "Error in running pdflatex command ('${R_PDFLATEXCMD}')"
+    do_cleanup
+    exit 1
+  fi
+  if test "${index}" != "false"; then
+    ## OK for R_MAKEINDEXCMD to fail.
+    ${R_MAKEINDEXCMD} Rd2
+    ${R_PDFLATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+    if test $status -gt 0; then
+      echo "Error in running pdflatex command ('${R_PDFLATEXCMD}')"
+      do_cleanup
+      exit 1
+    fi
+  fi
+  ${R_PDFLATEXCMD} ${R_TEXOPTS} Rd2 &&
+  ${R_PDFLATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+  if test $status -gt 0; then
+    echo "Error in running pdflatex command ('${R_PDFLATEXCMD}')"
+    do_cleanup
+    exit 1
+  fi
+else
+  ${R_LATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+  if test $status -gt 0; then
+    echo "Error in running latex command ('${R_LATEXCMD}')"
+    do_cleanup
+    exit 1
+  fi
+  if test "${index}" != "false"; then
+    ## OK for R_MAKEINDEXCMD to fail.
+    ${R_MAKEINDEXCMD} Rd2
+    ${R_LATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+    if test $status -gt 0; then
+      echo "Error in running latex command ('${R_LATEXCMD}')"
+      do_cleanup
+      exit 1
+    fi
+  fi
+  ${R_LATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+  if test $status -gt 0; then
+    echo "Error in running latex command ('${R_LATEXCMD}')"
+    do_cleanup
+    exit 1
+  fi
+fi
+if test ! -f Rd2.${out_ext}; then
+  echo "Error: no output file was created"
   do_cleanup
   exit 1
 fi
-
 cd ${start_dir}
 echo "Saving output to '${output}' ..."
 cp ${build_dir}/Rd2.${out_ext} ${output}
@@ -228,7 +282,7 @@ echo "Done"
 
 do_cleanup
 ${preview} ${output}
-exit 0
+exit ${status}
 
 ### Local Variables: ***
 ### mode: sh ***
