This commit was manufactured by cvs2svn to create tag 'R-0-61-3'.

diff --git a/etc/REMOVE.in b/etc/REMOVE.in
--- a/etc/REMOVE.in
+++ b/etc/REMOVE.in
@@ -2,52 +2,46 @@
 
 # ${RHOME}/etc/REMOVE for removing add-on packages
 # Usage:
-#	R REMOVE [options] [-l lib] pkg_1 ... pkg_n
+#	R REMOVE pkg [lib]
 
-VERSION="0.1-0"
-USAGE_MSG="Usage:  R REMOVE [options] [-l lib] pkg_1 ... pkg_n"
-lib=${RHOME}/library
-
-case ${1} in
-  -h|--help|-\?)
-    echo "${USAGE_MSG}"; exit 0 ;;
-  -V|--version)
-    echo "${VERSION}"; exit 0 ;;
-  -l)
-    lib=${2}; shift 2 ;;
-esac
-
-if test ${#} -eq 0; then
-  echo "${USAGE_MSG}"
-  exit 1
+if [ "$1" ]
+then
+    pkg=$1
+else
+    echo "usage:  R REMOVE pkg [lib]"
+    exit 1
 fi
 
-if test -d ${lib} -a -w ${lib}; then
-  cd ${lib}
-  lib=`pwd`
+lib=${2:-${RHOME}/library}
+if test -d ${lib}
+then
+    lib=`cd ${lib}; pwd`
 else    
-  echo "ERROR:  cannot cd to or remove from directory \`${lib}'"
-  exit 1
+    echo "Cannot find directory \`${lib}'"
+    exit 1
 fi    
 
-for pkg in $*; do
-  if test -d ${pkg}; then
+cd ${lib}
+if test -d ${pkg};
+then
     rm -rf ${pkg}
-  else
-    echo "Warning:  there is no pkg \`${pkg}' in lib \`${lib}'"
-    continue
-  fi
-done  
-
-cat */TITLE > LibIndex 2> /dev/null
-
-NO_PERL5=@NO_PERL5@
-if ${NO_PERL5}; then
-  echo "*** Cannot update the file"
-  echo "***    ${lib}/index.html"
-  echo "*** without Perl version 5.  Please delete the entries for"
-  echo "*** the packages you removed manually."
-  exit 2
+    cat */TITLE > LibIndex 2> /dev/null
+else
+    echo "There is no pkg \`${pkg}' in lib \`${lib}'"
+    exit 1
 fi
 
-${RHOME}/etc/build-help --htmllists
+NO_PERL5="@NO_PERL5@"
+
+if [ "$NO_PERL5" ]
+then
+    echo "*** Cannot update the file"
+    echo "***    ${RHOME}/library/index.html"
+    echo "*** without perl, version 5. Please remove the entry for"
+    echo "*** package \`${pkg}' manually."
+
+    exit 0
+fi
+
+$RHOME/etc/build-htmlpkglist
+
