This commit was manufactured by cvs2svn to create tag 'R-trunk-update-last'.

diff --git a/doc/manual/Makefile.in b/doc/manual/Makefile.in
--- a/doc/manual/Makefile.in
+++ b/doc/manual/Makefile.in
@@ -16,13 +16,12 @@ SOURCES_TEXI = R-FAQ.texi R-admin.texi R-data.texi R-exts.texi \
 DISTFILES = \
 	README \
 	Makefile.in Makefile.win \
-	R-defs.texi dir pdfcolor.tex texinfo.tex \
+	R-defs.texi dir texinfo.tex \
 	$(SOURCES_TEXI) \
 	resources.texi \
 	R-exts.R R-exts.c R-intro.R \
-	refman.top refman.bot \
-	ISBN
-SUBDIRS_WITH_NO_BUILD = images
+	refman.top refman.bot
+SUBDIRS = images
 
 OBJECTS_DVI = $(SOURCES_TEXI:.texi=.dvi)
 OBJECTS_HTML = $(SOURCES_TEXI:.texi=.html)
@@ -30,11 +29,7 @@ OBJECTS_INFO = $(SOURCES_TEXI:.texi=.info)
 OBJECTS_PDF = $(SOURCES_TEXI:.texi=.pdf)
 
 MAKEINFO = @MAKEINFO@
-MAKEINFO_HTML_OPTS = --html --no-split
-MAKEINFO_TEXT_OPTS = --number-sections --fill-column=76 --no-split --no-headers
-TEXI2HTML = $(MAKEINFO) $(MAKEINFO_HTML_OPTS)
-TEXI2TEXT = $(MAKEINFO) $(MAKEINFO_TEXT_OPTS)
-TEXI2DVI = $(top_builddir)/bin/texi2dvi --texinfo="@set UseExternalXrefs"
+TEXI2DVI = $(top_srcdir)/tools/texi2dvi --texinfo="@set UseExternalXrefs"
 TEXI2PDF = $(TEXI2DVI) --pdf
 PDFLATEX = @PDFLATEX@
 PDFTEX = @PDFTEX@
@@ -47,12 +42,7 @@ R_PAPERSIZE = @R_PAPERSIZE@
 R_RD4DVI = @R_RD4DVI@
 R_RD4PDF = @R_RD4PDF@
 
-texinputs_BASE = $(R_PKGS_BASE:=-pkg.tex)
-texinputs_RECOMMENDED = $(R_PKGS_RECOMMENDED_EXPANDED:=-pkg.tex)
-R_PKGS_refman = base methods tools @USE_RECOMMENDED_PACKAGES_TRUE@ grid
-refman_TEXINPUTS = $(R_PKGS_refman:=-pkg.tex)
-refman_DEPENDENCIES = version.tex $(top_srcdir)/share/texmf/Rd.sty
-fullrefman_TEXINPUTS = $(texinputs_BASE) @USE_RECOMMENDED_PACKAGES_TRUE@ $(texinputs_RECOMMENDED)
+pkgsrcs = $(R_PKGS:=-pkg.tex)
 
 texiincludes = version.texi $(srcdir)/R-defs.texi
 
@@ -62,7 +52,9 @@ texiincludes = version.texi $(srcdir)/R-defs.texi
 all: Makefile R docs
 
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
-	@cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
+	@cd $(top_builddir) && \
+	  CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= \
+	  $(SHELL) ./config.status
 
 R: Makefile @MAINTAINER_MODE_TRUE@ maintainer-build
 
@@ -70,46 +62,40 @@ docs: html
 
 .texi.dvi:
 	@if test "$(TEX)" = false; then \
-	  echo "ERROR: 'tex' needed but missing on your system."; \
+	  echo "ERROR: \`tex' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	TEXINPUTS="$(srcdir):$$TEXINPUTS" $(TEXI2DVI) $<
 .texi.html:
-	$(TEXI2HTML) -I$(srcdir) $< -o $@ || touch $@
+	$(MAKEINFO) --html -I$(srcdir) $< -o $@ || touch $@
 .texi.info:
 	@if test "$(MAKEINFO)" = false; then \
-	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
+	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
 	  exit 1; \
 	fi
 	$(MAKEINFO) -D UseExternalXrefs -I$(srcdir) $<
 .texi.pdf:
 	@if test "$(PDFTEX)" = false; then \
-	  echo "ERROR: 'pdftex' needed but missing on your system."; \
+	  echo "ERROR: \`pdftex' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	TEXINPUTS="$(srcdir):$$TEXINPUTS" $(TEXI2PDF) $<
 
 dvi: refman.dvi $(OBJECTS_DVI)
-refman.dvi: $(refman_DEPENDENCIES) stamp-refman-dvi
+refman.dvi: version.tex $(top_srcdir)/share/texmf/Rd.sty stamp-refman-dvi
 	@if test "$(LATEX)" = false; then \
-	  echo "ERROR: 'latex' needed but missing on your system."; \
+	  echo "ERROR: \`latex' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	@echo "DVI/LaTeX documentation: reference index ..."
 	@rm -f *.aux refman.toc refman.ind stamp-refman-dvi
-## <NOTE>
-## We do not make sure echo does not interpret backslash escapes.
-## Could be trouble ...
 	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
 	  echo "\\documentclass[$${opt}]{book}"; \
 	  opt="$${R_RD4DVI-$(R_RD4DVI)}"; \
 	  echo "\\usepackage[$${opt}]{Rd}"; \
 	  cat $(srcdir)/refman.top; \
-	  texinputs=`(for f in $(refman_TEXINPUTS); \
-	    do echo $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
+	  for p in $(R_PKGS); do echo "\\input{$${p}-pkg.tex}"; done; \
 	  cat $(srcdir)/refman.bot) > refman.tex
-## </NOTE>
 	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
 	  $(LATEX) '\nonstopmode\input{refman.tex}'
 	@-$(MAKEINDEX) refman
@@ -121,58 +107,18 @@ version.tex: Makefile $(top_srcdir)/date-stamp $(top_srcdir)/VERSION
 	@(v=`cat $(top_srcdir)/VERSION`; \
 	  v="$${v} (`sed 's|/|-|g' $(top_srcdir)/date-stamp`)"; \
 	  echo "$${v}") > $@
-stamp-refman-dvi: $(refman_TEXINPUTS)
+stamp-refman-dvi: $(pkgsrcs)
 	@touch $@
-$(texinputs_BASE): FORCE $(top_srcdir)/share/perl/build-help.pl
+$(pkgsrcs): FORCE $(top_srcdir)/share/perl/build-help.pl
 	@(pkg=`basename $@ -pkg.tex`; \
 	if $(PERL) $(top_srcdir)/tools/Rdnewer.pl \
 	    "$(top_srcdir)/src/library/$${pkg}" "$@"; then \
-	  echo "collecting LaTeX docs for package '$${pkg}' ..."; \
+	  echo "collecting LaTeX docs for package \`$${pkg}' ..."; \
 	  (cd $(top_builddir)/src/library && \
-	    OPTS="--latex" $(MAKE) R_PKGS_BASE="$${pkg}" DOCS); \
+	    OPTS="--latex" $(MAKE) R_PKGS="$${pkg}" DOCS); \
 	  $(PERL) $(top_srcdir)/tools/pkg2tex.pl $${pkg}; \
 	fi)
 FORCE:
-$(texinputs_RECOMMENDED): FORCE
-	@(pkg=`basename $@ -pkg.tex`; \
-	if find $@ -newer $(top_builddir)/library/$${pkg}/DESCRIPTION \
-	    -print 2> /dev/null | grep $@ > /dev/null; then :; else \
-	  echo "collecting LaTeX docs for package '$${pkg}' ..."; \
-	  RLIB="$(top_builddir)/library" \
-	    $(PERL) $(top_srcdir)/tools/pkg2tex.pl $${pkg}; \
-	fi)
-
-fullrefman.dvi: $(refman_DEPENDENCIES) stamp-fullrefman-dvi
-	@if test "$(LATEX)" = false; then \
-	  echo "ERROR: 'latex' needed but missing on your system."; \
-	  exit 1; \
-	fi
-	@echo "DVI/LaTeX documentation: full reference index ..."
-	@rm -f *.aux fullrefman.toc fullrefman.ind stamp-fullrefman-dvi
-	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
-	  echo "\\documentclass[$${opt}]{book}"; \
-	  opt="$${R_RD4DVI-$(R_RD4DVI)}"; \
-	  echo "\\usepackage[$${opt}]{Rd}"; \
-	  cat $(srcdir)/refman.top; \
-	  echo "\\part{}"; \
-	  texinputs=`(for f in $(refman_TEXINPUTS); \
-	    do echo $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
-	  echo "\\part{}"; \
-	  texinputs=`(for f in $(fullrefman_TEXINPUTS); \
-	    do echo $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $(refman_TEXINPUTS); do \
-	    texinputs=`echo "$${texinputs}" | sed "s/$${f}//"`; \
-	  done; \
-	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
-	  cat $(srcdir)/refman.bot) > fullrefman.tex
-	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
-	  $(LATEX) '\nonstopmode\input{fullrefman.tex}'
-	@-$(MAKEINDEX) fullrefman
-	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
-	  $(LATEX) '\nonstopmode\input{fullrefman.tex}'
-	@touch stamp-fullrefman-dvi
-stamp-fullrefman-dvi: $(fullrefman_TEXINPUTS)
 
 $(OBJECTS_DVI): $(srcdir)/texinfo.tex
 R-admin.dvi: $(texiincludes)
@@ -181,11 +127,8 @@ R-exts.dvi: $(texiincludes)
 version.texi: Makefile $(top_srcdir)/VERSION $(top_srcdir)/date-stamp
 	@echo "creating $(subdir)/$@"
 	@(v=`sed 's/\([^ ]*\).*/\1/' $(top_srcdir)/VERSION`; \
-	  echo "@set VERSIONno $${v}" > $@; \
 	  v="$${v} (`sed 's|/|-|g' $(top_srcdir)/date-stamp`)"; \
-	  echo "@set VERSION $${v}" >> $@; \
-	  rwv=`$(PERL) $(top_srcdir)/src/gnuwin32/fixed/rwver.pl $(top_srcdir)/VERSION`; \
-	  echo "@set RWVERSION $${rwv}" >> $@ )
+	  echo "@set VERSION $${v}" > $@)
 R-intro.dvi: stamp-images-eps $(texiincludes)
 stamp-images-eps:
 	@if test "$(BUILDDIR_IS_SRCDIR)" = no ; then \
@@ -211,26 +154,20 @@ R-intro.info: $(texiincludes)
 R-lang.info: $(texiincludes)
 
 pdf: refman.pdf $(OBJECTS_PDF)
-refman.pdf: $(refman_DEPENDENCIES) stamp-refman-pdf
+refman.pdf: version.tex $(top_srcdir)/share/texmf/Rd.sty stamp-refman-pdf
 	@if test "$(PDFLATEX)" = false; then \
-	  echo "ERROR: 'pdflatex' needed but missing on your system."; \
+	  echo "ERROR: \`pdflatex' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	@echo "PDF/LaTeX documentation: reference index ..."
 	@rm -f *.aux refman.toc refman.ind stamp-refman-pdf
-## <NOTE>
-## We do not make sure echo does not interpret backslash escapes.
-## Could be trouble ...
 	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
 	  echo "\\documentclass[$${opt}]{book}"; \
 	  opt="$${R_RD4PDF-$(R_RD4PDF)}"; \
 	  echo "\\usepackage[$${opt}]{Rd}"; \
 	  cat $(srcdir)/refman.top; \
-	  texinputs=`(for f in $(refman_TEXINPUTS); \
-	    do echo $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
+	  for p in $(R_PKGS); do echo "\\input{$${p}-pkg.tex}"; done; \
 	  cat $(srcdir)/refman.bot) > refman.tex
-## </NOTE>
 	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
 	  pool_size=500000 max_strings=50000 \
 	  $(PDFLATEX) '\nonstopmode\input{refman.tex}'
@@ -242,46 +179,10 @@ refman.pdf: $(refman_DEPENDENCIES) stamp-refman-pdf
 	  pool_size=500000 max_strings=50000 \
 	  $(PDFLATEX) '\nonstopmode\input{refman.tex}'
 	@touch stamp-refman-pdf
-stamp-refman-pdf: $(refman_TEXINPUTS)
+stamp-refman-pdf: $(pkgsrcs)
 	@touch $@
-fullrefman.pdf: $(refman_DEPENDENCIES) stamp-fullrefman-pdf
-	@if test "$(PDFLATEX)" = false; then \
-	  echo "ERROR: 'pdflatex' needed but missing on your system."; \
-	  exit 1; \
-	fi
-	@echo "PDF/LaTeX documentation: full reference index ..."
-	@rm -f *.aux fullrefman.toc fullrefman.ind stamp-fullrefman-pdf
-	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
-	  echo "\\documentclass[$${opt}]{book}"; \
-	  opt="$${R_RD4PDF-$(R_RD4PDF)}"; \
-	  echo "\\usepackage[$${opt}]{Rd}"; \
-	  cat $(srcdir)/refman.top; \
-	  echo "\\part{}"; \
-	  texinputs=`(for f in $(refman_TEXINPUTS); \
-	    do echo $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
-	  echo "\\part{}"; \
-	  texinputs=`(for f in $(fullrefman_TEXINPUTS); \
-	    do echo $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $(refman_TEXINPUTS); do \
-	    texinputs=`echo "$${texinputs}" | sed "s/$${f}//"`; \
-	  done; \
-	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
-	  cat $(srcdir)/refman.bot) > fullrefman.tex
-	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
-	  pool_size=500000 max_strings=50000 dest_names_size=50000 \
-	  $(PDFLATEX) '\nonstopmode\input{fullrefman.tex}'
-	@-$(MAKEINDEX) fullrefman
-	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
-	  pool_size=500000 max_strings=50000 dest_names_size=50000 \
-	  $(PDFLATEX) '\nonstopmode\input{fullrefman.tex}'
-	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
-	  pool_size=500000 max_strings=50000 dest_names_size=50000 \
-	  $(PDFLATEX) '\nonstopmode\input{fullrefman.tex}'
-	@touch stamp-fullrefman-pdf
-stamp-fullrefman-pdf: $(fullrefman_TEXINPUTS)
 
-$(OBJECTS_PDF): $(srcdir)/texinfo.tex $(srcdir)/pdfcolor.tex
+$(OBJECTS_PDF): $(srcdir)/texinfo.tex
 R-admin.pdf: $(texiincludes)
 R-data.pdf: $(texiincludes)
 R-exts.pdf: $(texiincludes)
@@ -323,7 +224,7 @@ install-info: info $(infodir)/dir
 	@for f in $(OBJECTS_INFO:.info=.info*); do \
 	  $(INSTALL_DATA) $${f} $(infodir); \
 	done
-	@echo "updating '$(infodir)/dir' ..."
+	@echo "updating \`$(infodir)/dir' ..."
 	@for f in $(OBJECTS_INFO); do \
 	  $(INSTALL_INFO) --info-dir=$(infodir) $(infodir)/$${f} \
 	    || echo "you need to adjust $(infodir)/dir manually"; \
@@ -367,16 +268,17 @@ clean:
 	@if test "$(BUILDDIR_IS_SRCDIR)" = no ; then \
 	  rm -rf $(INSTFILES) images; \
 	fi
-	-@rm -f *.aux *.cp *.cps *.dvi *.fn *.fns *.html *.info* \
+	@-rm -f *.aux *.cp *.cps *.dvi *.fn *.fns *.html *.info* \
 	  *.ky *.kys *.log *.out *.pdf *.pg *.pgs *.ps *.ps-2 *.tmp \
 	  *.toc *.tp *.vr *.vrs \
 	  *-pkg.tex refman.i?? refman.tex version.tex \
 	  version.texi
-	-@rm -f stamp-*
+	@rm -f stamp-*
 distclean: clean
-	-@rm -f Makefile
+	@-rm -f Makefile
 maintainer-clean: distclean
 
+MAKEINFO_TEXT_OPTS = --number-sections --fill-column=76 --no-split --no-headers
 maintainer-build: \
   $(top_srcdir)/FAQ \
   $(top_srcdir)/RESOURCES \
@@ -385,35 +287,34 @@ maintainer-build: \
   $(top_srcdir)/doc/html/R-admin.html
 $(top_srcdir)/FAQ: @MAINTAINER_MODE_TRUE@ $(srcdir)/R-FAQ.texi
 	@if test "$(MAKEINFO)" = false; then \
-	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
+	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
 	  exit 1; \
 	fi
-	$(TEXI2TEXT) $(srcdir)/R-FAQ.texi -o $@
+	$(MAKEINFO) $(MAKEINFO_TEXT_OPTS) $< -o $@
 $(top_srcdir)/doc/html/faq.html: @MAINTAINER_MODE_TRUE@ $(srcdir)/R-FAQ.texi
 	@if test "$(MAKEINFO)" = false; then \
-	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
+	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
 	  exit 1; \
 	fi
-	$(TEXI2HTML) --number-sections $(srcdir)/R-FAQ.texi -o $@
+	$(MAKEINFO) --html --number-sections $< -o $@
 $(top_srcdir)/RESOURCES: @MAINTAINER_MODE_TRUE@ $(srcdir)/resources.texi
 	@if test "$(MAKEINFO)" = false; then \
-	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
+	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
 	  exit 1; \
 	fi
-	$(TEXI2TEXT) $(srcdir)/resources.texi -o $@
+	$(MAKEINFO) $(MAKEINFO_TEXT_OPTS) $< -o $@
 $(top_srcdir)/doc/html/resources.html: @MAINTAINER_MODE_TRUE@ $(srcdir)/resources.texi
 	@if test "$(MAKEINFO)" = false; then \
-	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
+	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
 	  exit 1; \
 	fi
-	$(TEXI2HTML) --no-headers $(srcdir)/resources.texi -o $@
+	$(MAKEINFO) --html --no-headers $< -o $@
 $(top_srcdir)/doc/html/R-admin.html: @MAINTAINER_MODE_TRUE@ $(srcdir)/R-admin.texi $(texiincludes)
 	@if test "$(MAKEINFO)" = false; then \
-	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
+	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
 	  exit 1; \
 	fi
-	$(TEXI2HTML) --no-headers --number-sections -I$(srcdir) \
-	  $(srcdir)/R-admin.texi -o $@
+	$(MAKEINFO) --html --no-headers --number-sections -I$(srcdir) $< -o $@
 
 distdir: $(DISTFILES)
 	@for f in $(DISTFILES); do \
@@ -421,8 +322,10 @@ distdir: $(DISTFILES)
 	    || ln $(srcdir)/$${f} $(distdir)/$${f} 2>/dev/null \
 	    || cp -p $(srcdir)/$${f} $(distdir)/$${f}; \
 	done
-	@for d in $(SUBDIRS_WITH_NO_BUILD); do \
-	  ((cd $(srcdir); $(TAR) -c -f - --exclude=CVS $${d}) \
-	      | (cd $(distdir); $(TAR) -x -f -)) \
-	    || exit 1; \
+	@for d in $(SUBDIRS); do \
+	  if test -d $(srcdir)/$${d}; then \
+	    ((cd $(srcdir); $(TAR) -c -f - --exclude=CVS $${d}) \
+	        | (cd $(distdir); $(TAR) -x -f -)) \
+	      || exit 1; \
+	  fi; \
 	done
