Tag version 2.6.1

diff --git a/doc/manual/Makefile.in b/doc/manual/Makefile.in
--- a/doc/manual/Makefile.in
+++ b/doc/manual/Makefile.in
@@ -71,38 +71,38 @@ docs: html
 
 .texi.dvi:
 	@if test "$(TEX)" = false; then \
-	  $(ECHO) "ERROR: 'tex' needed but missing on your system."; \
+	  echo "ERROR: 'tex' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	@if test "$(TEXI2DVI)" = false; then \
-	  $(ECHO) "ERROR: 'texi2dvi' needed but missing on your system."; \
+	  echo "ERROR: 'texi2dvi' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	TEXINPUTS="$(srcdir):$$TEXINPUTS" $(TEXI2DVI) $<
 
 .texi.html:
 	@if test "$(MAKEINFO)" = false; then \
-	  $(ECHO) "'makeinfo' v4.7 or later needed to make HTML docs but missing on your system." ; \
-	  $(ECHO) "file $@ will be missing"; \
+	  echo "'makeinfo' v4.7 or later needed to make HTML docs but missing on your system." ; \
+	  echo "file $@ will be missing"; \
 	else \
-	  $(ECHO) "creating doc/manual/$@"; \
+	  echo "creating doc/manual/$@"; \
 	  $(TEXI2HTML) -D UseExternalXrefs -I$(srcdir) $< -o $@ || touch $@; \
 	fi
 
 .texi.info:
 	@if test "$(MAKEINFO)" = false; then \
-	  $(ECHO) "ERROR: 'makeinfo' v4.7 or later needed but missing on your system."; \
+	  echo "ERROR: 'makeinfo' v4.7 or later needed but missing on your system."; \
 	  exit 1; \
 	fi
 	$(MAKEINFO) --enable-encoding -D UseExternalXrefs -I$(srcdir) $<
 
 .texi.pdf:
 	@if test "$(PDFTEX)" = false; then \
-	  $(ECHO) "ERROR: 'pdftex' needed but missing on your system."; \
+	  echo "ERROR: 'pdftex' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	@if test "$(TEXI2DVI)" = false; then \
-	  $(ECHO) "ERROR: 'texi2dvi' needed but missing on your system."; \
+	  echo "ERROR: 'texi2dvi' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	TEXINPUTS="$(srcdir):$$TEXINPUTS" $(TEXI2PDF) $<
@@ -116,10 +116,10 @@ R-admin.html: $(srcdir)/R-admin.texi
 	  cp "$(top_srcdir)/doc/html/R-admin.html" R-admin.html ; \
 	else \
 	  if test "$(MAKEINFO)" = false; then \
-	    $(ECHO) "'makeinfo' v4.7 or later needed to make HTML docs but missing on your system." ; \
-	    $(ECHO) "file $@ will be missing"; \
+	    echo "'makeinfo' v4.7 or later needed to make HTML docs but missing on your system." ; \
+	    echo "file $@ will be missing"; \
 	  else \
-	    $(ECHO) "creating doc/manual/$@"; \
+	    echo "creating doc/manual/$@"; \
 	    $(TEXI2HTML) -I$(srcdir) $(srcdir)/R-admin.texi -o $@ || touch $@;\
 	  fi ; \
 	fi
@@ -127,23 +127,23 @@ R-admin.html: $(srcdir)/R-admin.texi
 dvi: refman.dvi $(OBJECTS_DVI)
 refman.dvi: $(refman_DEPENDENCIES) stamp-refman-dvi
 	@if test "$(LATEX)" = false; then \
-	  $(ECHO) "ERROR: 'latex' needed but missing on your system."; \
+	  echo "ERROR: 'latex' needed but missing on your system."; \
 	  exit 1; \
 	fi
-	@$(ECHO) "DVI/LaTeX documentation: reference index ..."
+	@echo "DVI/LaTeX documentation: reference index ..."
 	@rm -f *.aux refman.toc refman.ind stamp-refman-dvi
 ## <NOTE>
-## We do not make sure $(ECHO) does not interpret backslash escapes.
+## We do not make sure echo does not interpret backslash escapes.
 ## Could be trouble ...
 	@(opt="$(R_PAPERSIZE)paper"; \
-	  $(ECHO) "\\documentclass[$${opt}]{book}"; \
+	  echo "\\documentclass[$${opt}]{book}"; \
 	  opt="$(R_RD4DVI)"; \
-	  $(ECHO) "\\usepackage[$${opt}]{Rd}"; \
-	  $(ECHO) "\\usepackage[latin1]{inputenc}"; \
+	  echo "\\usepackage[$${opt}]{Rd}"; \
+	  echo "\\usepackage[latin1]{inputenc}"; \
 	  cat $(srcdir)/refman.top; \
 	  texinputs=`(for f in $(refman_TEXINPUTS); \
-	    do $(ECHO) $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $${texinputs}; do $(ECHO) "\\input{$${f}}"; done; \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
 	  cat $(srcdir)/refman.bot) > refman.tex
 ## </NOTE>
 	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
@@ -154,10 +154,10 @@ refman.dvi: $(refman_DEPENDENCIES) stamp-refman-dvi
 	@touch stamp-refman-dvi
 
 version.tex: Makefile $(top_builddir)/SVN-REVISION $(top_builddir)/VERSION
-	@$(ECHO) "creating $(subdir)/$@"
+	@echo "creating $(subdir)/$@"
 	@(v=`cat $(top_srcdir)/VERSION`; \
 	  v="$${v} (`sed -e 1d -e 's/^Last Changed Date: //' $(top_builddir)/SVN-REVISION`)"; \
-	  $(ECHO) "$${v}") > $@
+	  echo "$${v}") > $@
 
 stamp-refman-dvi: $(refman_TEXINPUTS)
 	@touch $@
@@ -167,7 +167,7 @@ $(texinputs_BASE): FORCE $(top_srcdir)/share/perl/build-help.pl
 	@(pkg=`basename $@ -pkg.tex`; \
 	if $(PERL) $(top_srcdir)/tools/Rdnewer.pl \
 	    "$(top_srcdir)/src/library/$${pkg}" "$@"; then \
-	  $(ECHO) "collecting LaTeX docs for package '$${pkg}' ..."; \
+	  echo "collecting LaTeX docs for package '$${pkg}' ..."; \
 	  (cd $(top_builddir)/src/library && \
 	    $(MAKE) R_PKGS_BASE="$${pkg}" latex); \
 	  PERL5LIB=$(top_srcdir)/share/perl $(PERL) $(top_srcdir)/tools/pkg2tex.pl $${pkg}; \
@@ -178,35 +178,35 @@ $(texinputs_RECOMMENDED): FORCE
 	@(pkg=`basename $@ -pkg.tex`; \
 	if find $@ -newer $(top_builddir)/library/$${pkg}/DESCRIPTION \
 	    -print 2> /dev/null | grep $@ > /dev/null; then :; else \
-	  $(ECHO) "collecting LaTeX docs for package '$${pkg}' ..."; \
+	  echo "collecting LaTeX docs for package '$${pkg}' ..."; \
 	  RLIB="$(top_builddir)/library" \
 	    PERL5LIB=$(top_srcdir)/share/perl $(PERL) $(top_srcdir)/tools/pkg2tex.pl $${pkg}; \
 	fi)
 
 fullrefman.dvi: $(refman_DEPENDENCIES) stamp-fullrefman-dvi
 	@if test "$(LATEX)" = false; then \
-	  $(ECHO) "ERROR: 'latex' needed but missing on your system."; \
+	  echo "ERROR: 'latex' needed but missing on your system."; \
 	  exit 1; \
 	fi
-	@$(ECHO) "DVI/LaTeX documentation: full reference index ..."
+	@echo "DVI/LaTeX documentation: full reference index ..."
 	@rm -f *.aux fullrefman.toc fullrefman.ind stamp-fullrefman-dvi
 	@(opt="$(R_PAPERSIZE)paper"; \
-	  $(ECHO) "\\documentclass[$${opt}]{book}"; \
+	  echo "\\documentclass[$${opt}]{book}"; \
 	  opt="$(R_RD4DVI)"; \
-	  $(ECHO) "\\usepackage[$${opt}]{Rd}"; \
-	  $(ECHO) "\\usepackage[latin1]{inputenc}"; \
+	  echo "\\usepackage[$${opt}]{Rd}"; \
+	  echo "\\usepackage[latin1]{inputenc}"; \
 	  cat $(srcdir)/refman.top; \
-	  $(ECHO) "\\part{}"; \
+	  echo "\\part{}"; \
 	  texinputs=`(for f in $(refman_TEXINPUTS); \
-	    do $(ECHO) $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $${texinputs}; do $(ECHO) "\\input{$${f}}"; done; \
-	  $(ECHO) "\\part{}"; \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
+	  echo "\\part{}"; \
 	  texinputs=`(for f in $(fullrefman_TEXINPUTS); \
-	    do $(ECHO) $${f}; done) | LC_COLLATE=C sort`; \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
 	  for f in $(refman_TEXINPUTS); do \
-	    texinputs=`$(ECHO) "$${texinputs}" | sed "s/\\<$${f}\\>//"`; \
+	    texinputs=`echo "$${texinputs}" | sed "s/\\<$${f}\\>//"`; \
 	  done; \
-	  for f in $${texinputs}; do $(ECHO) "\\input{$${f}}"; done; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
 	  cat $(srcdir)/refman.bot) > fullrefman.tex
 	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
 	  $(LATEX) '\nonstopmode\input{fullrefman.tex}'
@@ -221,15 +221,15 @@ R-data.dvi: $(texiincludes)
 R-exts.dvi: $(texiincludes)
 R-ints.dvi: $(texiincludes)
 version.texi: Makefile $(top_srcdir)/VERSION $(top_builddir)/SVN-REVISION
-	@$(ECHO) "creating $(subdir)/$@"
+	@echo "creating $(subdir)/$@"
 	@(v=`sed 's/\([^ ]*\).*/\1/' $(top_srcdir)/VERSION`; \
-	  $(ECHO) "@set VERSIONno $${v}" > $@; \
+	  echo "@set VERSIONno $${v}" > $@; \
 	  v="$${v} (`sed -e 1d -e 's/^Last Changed Date: //' $(top_builddir)/SVN-REVISION`)"; \
-	  $(ECHO) "@set VERSION $${v}" >> $@; \
+	  echo "@set VERSION $${v}" >> $@; \
 	  rwv=`$(PERL) $(top_srcdir)/src/gnuwin32/fixed/rwver.pl $(top_srcdir)/VERSION`; \
-	  $(ECHO) "@set RWVERSION $${rwv}" >> $@ )
+	  echo "@set RWVERSION $${rwv}" >> $@ )
 	@if test "$(R_PAPERSIZE)" = "a4"; then \
-	  $(ECHO) "@afourpaper" >> $@ ; \
+	  echo "@afourpaper" >> $@ ; \
 	fi
 
 R-intro.dvi: stamp-images-eps $(texiincludes)
@@ -261,23 +261,23 @@ R-lang.info: $(texiincludes)
 pdf: refman.pdf $(OBJECTS_PDF)
 refman.pdf: $(refman_DEPENDENCIES) stamp-refman-pdf
 	@if test "$(PDFLATEX)" = false; then \
-	  $(ECHO) "ERROR: 'pdflatex' needed but missing on your system."; \
+	  echo "ERROR: 'pdflatex' needed but missing on your system."; \
 	  exit 1; \
 	fi
-	@$(ECHO) "PDF/LaTeX documentation: reference index ..."
+	@echo "PDF/LaTeX documentation: reference index ..."
 	@rm -f *.aux refman.toc refman.ind stamp-refman-pdf
 ## <NOTE>
-## We do not make sure $(ECHO) does not interpret backslash escapes.
+## We do not make sure echo does not interpret backslash escapes.
 ## Could be trouble ...
 	@(opt="$(R_PAPERSIZE)paper"; \
-	  $(ECHO) "\\documentclass[$${opt}]{book}"; \
+	  echo "\\documentclass[$${opt}]{book}"; \
 	  opt="$(R_RD4PDF)"; \
-	  $(ECHO) "\\usepackage[$${opt}]{Rd}"; \
-	  $(ECHO) "\\usepackage[latin1]{inputenc}"; \
+	  echo "\\usepackage[$${opt}]{Rd}"; \
+	  echo "\\usepackage[latin1]{inputenc}"; \
 	  cat $(srcdir)/refman.top; \
 	  texinputs=`(for f in $(refman_TEXINPUTS); \
-	    do $(ECHO) $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $${texinputs}; do $(ECHO) "\\input{$${f}}"; done; \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
 	  cat $(srcdir)/refman.bot) > refman.tex
 ## </NOTE>
 	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
@@ -295,28 +295,28 @@ stamp-refman-pdf: $(refman_TEXINPUTS)
 	@touch $@
 fullrefman.pdf: $(refman_DEPENDENCIES) stamp-fullrefman-pdf
 	@if test "$(PDFLATEX)" = false; then \
-	  $(ECHO) "ERROR: 'pdflatex' needed but missing on your system."; \
+	  echo "ERROR: 'pdflatex' needed but missing on your system."; \
 	  exit 1; \
 	fi
-	@$(ECHO) "PDF/LaTeX documentation: full reference index ..."
+	@echo "PDF/LaTeX documentation: full reference index ..."
 	@rm -f *.aux fullrefman.toc fullrefman.ind stamp-fullrefman-pdf
 	@(opt="$(R_PAPERSIZE)paper"; \
-	  $(ECHO) "\\documentclass[$${opt}]{book}"; \
+	  echo "\\documentclass[$${opt}]{book}"; \
 	  opt="$(R_RD4PDF)"; \
-	  $(ECHO) "\\usepackage[$${opt}]{Rd}"; \
-	  $(ECHO) "\\usepackage[latin1]{inputenc}"; \
+	  echo "\\usepackage[$${opt}]{Rd}"; \
+	  echo "\\usepackage[latin1]{inputenc}"; \
 	  cat $(srcdir)/refman.top; \
-	  $(ECHO) "\\part{}"; \
+	  echo "\\part{}"; \
 	  texinputs=`(for f in $(refman_TEXINPUTS); \
-	    do $(ECHO) $${f}; done) | LC_COLLATE=C sort`; \
-	  for f in $${texinputs}; do $(ECHO) "\\input{$${f}}"; done; \
-	  $(ECHO) "\\part{}"; \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
+	  echo "\\part{}"; \
 	  texinputs=`(for f in $(fullrefman_TEXINPUTS); \
-	    do $(ECHO) $${f}; done) | LC_COLLATE=C sort`; \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
 	  for f in $(refman_TEXINPUTS); do \
-	    texinputs=`$(ECHO) "$${texinputs}" | sed "s/\\<$${f}\\>//"`; \
+	    texinputs=`echo "$${texinputs}" | sed "s/\\<$${f}\\>//"`; \
 	  done; \
-	  for f in $${texinputs}; do $(ECHO) "\\input{$${f}}"; done; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
 	  cat $(srcdir)/refman.bot) > fullrefman.tex
 	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
 	  pool_size=500000 max_strings=50000 dest_names_size=50000 \
@@ -345,12 +345,12 @@ R-lang.pdf: $(texiincludes)
 
 install: install-message installdirs install-html
 install-message:
-	@$(ECHO) "installing $(subdir) ..."
+	@echo "installing $(subdir) ..."
 installdirs:
 	@$(MKINSTALLDIRS) "$(DESTDIR)$(rdocdir)/manual"
 install-strip: install
 install-dvi: dvi installdirs install-images-eps
-	@$(ECHO) "installing R manuals in DVI format ..."
+	@echo "installing R manuals in DVI format ..."
 	@for f in *.dvi; do \
 	  $(INSTALL_DATA) $${f} "$(DESTDIR)$(rdocdir)/manual"; \
 	done
@@ -372,18 +372,18 @@ install-html:
 	  fi \
 	done
 install-info: info $(DESTDIR)$(infodir)/dir
-	@$(ECHO) "installing R info pages ..."
+	@echo "installing R info pages ..."
 	@for f in $(OBJECTS_INFO:.info=.info*); do \
 	  $(INSTALL_DATA) $${f} "$(DESTDIR)$(infodir)"; \
 	  $(R_GZIPCMD) -f "$(DESTDIR)$(infodir)/$${f}"; \
 	done
-	@$(ECHO) "updating '$(infodir)/dir' ..."
+	@echo "updating '$(infodir)/dir' ..."
 	@for f in $(OBJECTS_INFO); do \
 	  $(INSTALL_INFO) --info-dir=$(DESTDIR)$(infodir) $(DESTDIR)$(infodir)/$${f} \
-	    || $(ECHO) "you need to adjust $(infodir)/dir manually"; \
+	    || echo "you need to adjust $(infodir)/dir manually"; \
 	done
 install-pdf: pdf installdirs
-	@$(ECHO) "installing R manuals in PDF format ..."
+	@echo "installing R manuals in PDF format ..."
 	@for f in *.pdf; do \
 	  $(INSTALL_DATA) $${f} "$(DESTDIR)$(rdocdir)/manual"; \
 	done
@@ -397,24 +397,24 @@ uninstall:
 	     || test -f "$(DESTDIR)$(infodir)/R-data.info.gz"; then \
 	  $(MAKE) uninstall-info; \
 	fi
-	@$(ECHO) "uninstalling $(subdir) ..."
+	@echo "uninstalling $(subdir) ..."
 	@rm -rf "$(DESTDIR)$(rdocdir)/manual"
 uninstall-dvi:
-	@$(ECHO) "uninstalling R manuals in DVI format ..."
+	@echo "uninstalling R manuals in DVI format ..."
 	@-rm -f "$(DESTDIR)$(rdocdir)/manual"/images/*.eps
 	@-rmdir "$(DESTDIR)$(rdocdir)/manual"/images
 	@-rm -f "$(DESTDIR)$(rdocdir)/manual"/*.dvi
 uninstall-info:
-	@$(ECHO) "uninstalling R info pages ..."
+	@echo "uninstalling R info pages ..."
 	@for f in $(OBJECTS_INFO); do \
 	  $(INSTALL_INFO) --remove --info-dir=$(DESTDIR)$(infodir) $${f} \
-	    || $(ECHO) "you need to adjust $(infodir)/dir manually"; \
+	    || echo "you need to adjust $(infodir)/dir manually"; \
 	done
 	@for f in $(OBJECTS_INFO:.info=.info*); do \
 	  rm -f "$(DESTDIR)$(infodir)/$${f}" "$(DESTDIR)$(infodir)/$${f}.gz" ; \
 	done
 uninstall-pdf:
-	@$(ECHO) "uninstalling R manuals in PDF format ..."
+	@echo "uninstalling R manuals in PDF format ..."
 	@-rm -f "$(DESTDIR)$(rdocdir)/manual"/*.pdf
 
 mostlyclean: clean
@@ -444,7 +444,7 @@ distdir: $(DISTFILES)
 	    || exit 1; \
 	done
 	@if test "$(MAKEINFO)" = false; then \
-	  $(ECHO) "ERROR: 'makeinfo' v4.7 or later needed but missing on your system."; \
+	  echo "ERROR: 'makeinfo' v4.7 or later needed but missing on your system."; \
 	  exit 1; \
 	fi
 #	$(distdir)/doc/html has already been created
@@ -460,15 +460,15 @@ distdir: $(DISTFILES)
 front-matter: ${top_builddir}/doc/RESOURCES ${top_builddir}/doc/FAQ
 
 ${top_builddir}/doc/RESOURCES: $(srcdir)/resources.texi
-	@$(ECHO) "creating RESOURCES"
+	@echo "creating RESOURCES"
 	@$(TEXI2TEXT) $(srcdir)/resources.texi -o $@
 
 ${top_builddir}/doc/FAQ: $(srcdir)/R-FAQ.texi
-	@$(ECHO) "creating FAQ"
+	@echo "creating FAQ"
 	@$(TEXI2TEXT) $(srcdir)/R-FAQ.texi -o $@
 
 html-non-svn: ../html/resources.html
 
 ../html/resources.html: $(srcdir)/resources.texi
-	@$(ECHO) "creating doc/html/resources.html"
+	@echo "creating doc/html/resources.html"
 	@$(TEXI2HTML) --no-headers $(srcdir)/resources.texi -o $@
diff --git a/src/library/Makefile.in b/src/library/Makefile.in
--- a/src/library/Makefile.in
+++ b/src/library/Makefile.in
@@ -11,7 +11,7 @@ subdir = src/library
 include $(top_builddir)/Makeconf
 
 distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)
-DISTFILES = Makefile.in eof_file
+DISTFILES = Makefile.in
 
 SUBDIRS = profile $(R_PKGS_BASE) Recommended
 
@@ -40,47 +40,55 @@ R:
 	@for pkg in profile $(R_PKGS_BASE); do \
 	  (cd $${pkg} && $(MAKE)) || exit 1; \
 	done
-	@$(ECHO) "tools:::.vinstall_package_descriptions_as_RDS(\"$(top_builddir)/library\", \"$(R_PKGS_BASE)\")" | \
+	@echo "tools:::.vinstall_package_descriptions_as_RDS(\"$(top_builddir)/library\", \"$(R_PKGS_BASE)\")" | \
 	  R_DEFAULT_PACKAGES=tools LC_ALL=C $(R_EXE) --slave > /dev/null
-	@$(ECHO) "installing parsed NAMESPACE files"
+	@echo "installing parsed NAMESPACE files"
 	@rm -f $(top_builddir)/library/tools/Meta/nsInfo.rds
-	@$(ECHO) "tools:::.vinstall_package_namespaces_as_RDS(\"$(top_builddir)/library\", \"$(R_PKGS_BASE)\")" | \
+	@echo "tools:::.vinstall_package_namespaces_as_RDS(\"$(top_builddir)/library\", \"$(R_PKGS_BASE)\")" | \
 	  R_DEFAULT_PACKAGES=tools LC_ALL=C $(R_EXE) --slave > /dev/null
 	@$(INSTALL_DATA) $(top_srcdir)/doc/html/R.css \
 	  $(top_builddir)/library
 
 docs:
-	@$(ECHO) "building all R object docs (text, HTML, LaTeX, examples)"
+	@echo "building all R object docs (text, HTML, LaTeX, examples)"
 	@$(MAKE) help-indices
 	@$(MAKE) Rdfiles
 	@$(MAKE) indices
 	@touch stamp-docs
 
 help-indices:
+	@if @NO_PERL5@; then \
+	  echo "you need Perl version 5 to build the R object docs"; \
+	  exit 1; \
+	fi
 	@for pkg in $(R_PKGS_BASE); do \
 	  $(R_CMD_BUILD_HELP) $(R_CMD_BUILD_HELP_OPTS) --index $(srcdir)/$${pkg}; \
 	done
 Rdfiles:
+	@if @NO_PERL5@; then \
+	  echo "you need Perl version 5 to build the R object docs"; \
+	  exit 1; \
+	fi
 	@for pkg in $(R_PKGS_BASE); do \
 	  $(R_CMD_BUILD_HELP) $(R_CMD_BUILD_HELP_OPTS) $(srcdir)/$${pkg}; \
 	done
 vignettes:
 	@if test "$(PDFLATEX)" = false; then \
-          $(ECHO) "WARNING: cannot build/update package vignettes."; \
-	  $(ECHO) "'pdflatex' needed but missing on your system."; \
+          echo "WARNING: cannot build/update package vignettes."; \
+	  echo "'pdflatex' needed but missing on your system."; \
 	else \
 	  for pkg in $(R_PKGS_BASE); do \
 	    if test -d "$(srcdir)/$${pkg}/inst/doc"; then \
-	      $(ECHO) "building/updating vignettes for package '$${pkg}' ..."; \
-	      ($(ECHO) "tools:::.install_package_vignettes(\"$(srcdir)/$${pkg}\", \"$(top_builddir)/library/$${pkg}\")") | \
+	      echo "building/updating vignettes for package '$${pkg}' ..."; \
+	      (echo "tools:::.install_package_vignettes(\"$(srcdir)/$${pkg}\", \"$(top_builddir)/library/$${pkg}\")") | \
 	          R_DEFAULT_PACKAGES="utils,tools" LC_ALL=C \
 	            $(R_EXE) --slave > /dev/null; \
 	    fi; \
 	  done; \
 	fi
 indices:
-	@$(ECHO) "building/updating package indices ..."
-	@$(ECHO) "tools:::.vinstall_package_indices(\"$(srcdir)\", \"$(top_builddir)/library\", \"$(R_PKGS_BASE)\")" | \
+	@echo "building/updating package indices ..."
+	@echo "tools:::.vinstall_package_indices(\"$(srcdir)\", \"$(top_builddir)/library\", \"$(R_PKGS_BASE)\")" | \
 	  R_DEFAULT_PACKAGES=tools LC_ALL=C $(R_EXE) --slave > /dev/null
 	@cat $(top_builddir)/library/*/CONTENTS \
 	  > $(top_builddir)/doc/html/search/index.txt
@@ -89,7 +97,7 @@ help:
 	@$(MAKE) Rdfiles R_CMD_BUILD_HELP_OPTS="--txt"
 html:
 	@$(MAKE) Rdfiles R_CMD_BUILD_HELP_OPTS="--html"
-	@$(ECHO) "tools:::unix.packages.html(.Library)" | \
+	@echo "tools:::unix.packages.html(.Library)" | \
 	  R_DEFAULT_PACKAGES=NULL LC_ALL=C "${R_EXE}" >/dev/null
 latex:
 	@$(MAKE) Rdfiles R_CMD_BUILD_HELP_OPTS="--latex"
@@ -97,12 +105,12 @@ examples:
 	@$(MAKE) Rdfiles R_CMD_BUILD_HELP_OPTS="--example"
 
 install: installdirs
-	@$(ECHO) "installing packages ..."
+	@echo "installing packages ..."
 	@cp -r $(top_builddir)/library "$(DESTDIR)$(rhome)" || \
 	  (cd $(top_builddir)/library; \
 	    $(TAR) cf - . | (cd "$(DESTDIR)$(rhome)/library"; $(TAR) xmof -))
-	@$(ECHO) "  building HTML index ..."
-	@$(ECHO) "tools:::unix.packages.html(.Library, docdir=\"$(DESTDIR)${rdocdir}\")" | \
+	@echo "  building HTML index ..."
+	@echo "tools:::unix.packages.html(.Library, docdir=\"$(DESTDIR)${rdocdir}\")" | \
           R_DEFAULT_PACKAGES=NULL LC_ALL=C ${R_EXE} >/dev/null
 installdirs:
 	@$(MKINSTALLDIRS) "$(DESTDIR)$(rhome)/library"
@@ -112,12 +120,12 @@ install-strip:
 	  $(STRIP_LIBS) "$(DESTDIR)$(rhome)/library"/*/libs/*${SHLIB_EXT}; \
 	fi
 uninstall:
-	@$(ECHO) "uninstalling packages ..."
+	@echo "uninstalling packages ..."
 	@(cd "$(DESTDIR)$(rhome)/library"; \
 	  for p in $(R_PKGS); do rm -rf $${p}; done)
 	@rm -f "$(DESTDIR)$(rhome)/library/R.css"
 	@rmdir "$(DESTDIR)$(rhome)/library" 2>/dev/null \
-          || $(ECHO) "  subdir $(DESTDIR)$(rhome)/library not removed"
+          || echo "  subdir $(DESTDIR)$(rhome)/library not removed"
 
 
 mostlyclean: clean
diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -19,8 +19,7 @@ test-src-gct = \
 	arith.R \
 	lm-tests.R \
 	ok-errors.R \
-	method-dispatch.R \
-	datasets.R
+	method-dispatch.R
 test-src-strict-1 = \
 	$(test-src-gct) \
 	d-p-q-r-tests.R
@@ -28,6 +27,7 @@ test-src-strict-auto =
 test-src-sloppy-1 = \
 	complex.R \
 	print-tests.R \
+	datasets.R \
 	lapack.R
 test-src-sloppy-auto =
 
@@ -133,69 +133,69 @@ stamp-R: $(top_builddir)/bin/exec@R_ARCH@/R \
 Makedeps: Makefile
 	@(for f in $(test-src) $(test-src-reg) $(test-src-demo); do \
 	    if test -f $(srcdir)/$${f}out.save ; then \
-	      $(ECHO) "$${f}out: $${f} \$$(srcdir)/$${f}out.save \$$(FORCE)"; \
+	      echo "$${f}out: $${f} \$$(srcdir)/$${f}out.save \$$(FORCE)"; \
 	    else \
-	      $(ECHO) "$${f}out: $${f} \$$(FORCE)"; \
+	      echo "$${f}out: $${f} \$$(FORCE)"; \
 	    fi; \
 	    if test -f $(srcdir)/$${f}in; then \
-	      $(ECHO) "$${f}: \$$(srcdir)/$${f}in stamp-R"; \
+	      echo "$${f}: \$$(srcdir)/$${f}in stamp-R"; \
 	    fi; \
 	  done) >> Makefile
 	@touch $@
 FORCE:
 
 .Rin.R:
-	@$(ECHO) "creating '$@'"
+	@echo "creating '$@'"
 	@$(R) < $< > /dev/null
 
 .R.Rout:
 	@rm -f $@ $@.fail
-	@$(ECHO) $(ECHO_N) "running code in '$<' ...$(ECHO_C)"
+	@echo $(ECHO_N) "running code in '$<' ...$(ECHO_C)"
 	@$(R) < $< > $@ 2>&1 || (mv $@ $@.fail && exit 1)
-	@$(ECHO) "$(ECHO_T) OK"
+	@echo "$(ECHO_T) OK"
 	@if test -f $(srcdir)/$@.save ; then \
 	  mv $@ $@.fail; \
-	  $(ECHO) $(ECHO_N) \
+	  echo $(ECHO_N) \
 	    "comparing '$@' to '$(srcdir)/$@.save' ...$(ECHO_C)"; \
 	  $(RDIFF) $@.fail $(srcdir)/$@.save $(RVAL_IF_DIFF) || exit 1; \
 	  mv $@.fail $@; \
-	  $(ECHO) "$(ECHO_T) OK"; \
+	  echo "$(ECHO_T) OK"; \
 	fi
 
 reg-plot.Rout: reg-plot.R
 	@rm -f $@ $@.fail
-	@$(ECHO) $(ECHO_N) "running code in '$<' ...$(ECHO_C)"
+	@echo $(ECHO_N) "running code in '$<' ...$(ECHO_C)"
 	@$(R) < $< > $@ 2>&1 || (mv $@ $@.fail && exit 1)
-	@$(ECHO) "$(ECHO_T) OK"
+	@echo "$(ECHO_T) OK"
 	@if test -f $(srcdir)/$@.save ; then \
 	  mv $@ $@.fail; \
-	  $(ECHO) $(ECHO_N) \
+	  echo $(ECHO_N) \
 	    "comparing '$@' to '$(srcdir)/$@.save' ...$(ECHO_C)"; \
 	  $(RDIFF) $@.fail $(srcdir)/$@.save $(RVAL_IF_DIFF) || exit 1; \
 	  mv $@.fail $@; \
-	  $(ECHO) "$(ECHO_T) OK"; \
+	  echo "$(ECHO_T) OK"; \
 	fi
-	@$(ECHO) $(ECHO_N) \
+	@echo $(ECHO_N) \
 	  "comparing 'reg-plot.ps' to '$(srcdir)/reg-plot.ps.save' ...$(ECHO_C)"
 	@$(RDIFF) reg-plot.ps $(srcdir)/reg-plot.ps.save $(RVAL_IF_DIFF)
-	@$(ECHO) "$(ECHO_T) OK"
+	@echo "$(ECHO_T) OK"
 
 .R.Rout-gct:
-	@$(ECHO) "running gctorture() + '$<'"
-	@($(ECHO) '.ptime <- proc.time(); gctorture()' ; \
+	@echo "running gctorture() + '$<'"
+	@(echo '.ptime <- proc.time(); gctorture()' ; \
 	  cat $< $(srcdir)/gct-foot.R) | $(R) > $@ 2>&1
 	@mv $@ $@.fail; Ro=`basename $@ .Rout-gct`.Rout; \
 	  if test ! -r $${Ro}; then $(MAKE) $${Ro}; fi; \
-	  $(ECHO) $(ECHO_N) "comparing '$@' to '$${Ro}' ...$(ECHO_C)"; \
+	  echo $(ECHO_N) "comparing '$@' to '$${Ro}' ...$(ECHO_C)"; \
 	  grep -v 'gctorture()' $@.fail | $(RDIFF) - $${Ro} 1 || exit 1; \
 	  mv $@.fail $@; \
-	  $(ECHO) "$(ECHO_T) OK"
+	  echo "$(ECHO_T) OK"
 
 R-valgrind = $(R) --debugger="valgrind --tool=memcheck"
 
 .R.Rout-valgct:
-	@$(ECHO) "running gctorture() + valgrind + '$<'"
-	@($(ECHO) '.ptime <- proc.time(); gctorture()' ; \
+	@echo "running gctorture() + valgrind + '$<'"
+	@(echo '.ptime <- proc.time(); gctorture()' ; \
 	  cat $< $(srcdir)/gct-foot.R) | $(R-valgrind) > $@ 2>&1
 	grep "==[0-9]*==" $@
 
@@ -219,18 +219,18 @@ test-Examples-Recommended:
 test-Specific-strict: $(test-out-strict)
 test-Specific-sloppy: $(test-out-sloppy)
 test-Specific:
-	@$(ECHO) "updating test dependencies"
+	@echo "updating test dependencies"
 	@$(MAKE) Makedeps
-	@$(ECHO) "running strict specific tests"
+	@echo "running strict specific tests"
 	@$(MAKE) test-Specific-strict RVAL_IF_DIFF=1
-	@$(ECHO) "running sloppy specific tests"
+	@echo "running sloppy specific tests"
 	@$(MAKE) test-Specific-sloppy RVAL_IF_DIFF=0
 
 test-Packages:
 	@for p in $(R_PKGS_BASE); do \
-	  $(ECHO) "checking package '$${p}'"; \
+	  echo "checking package '$${p}'"; \
 	  $(top_builddir)/bin/R CMD check --install=skip \
-	    $(top_srcdir)/src/library/$${p} || $(ECHO); \
+	    $(top_srcdir)/src/library/$${p} || echo; \
 	done
 
 test-Gct: $(test-out-gct)
@@ -238,54 +238,54 @@ test-Gct: $(test-out-gct)
 test-Vgct: $(test-out-valgct)
 
 test-Docs:
-	@$(ECHO) "running tests of documentation examples"
+	@echo "running tests of documentation examples"
 	@cp ${top_srcdir}/doc/manual/*.R .
-	@$(MAKE) R-intro.Rout RVAL_IF_DIFF=0
+	@$(MAKE) R-intro.Rout RVAL_IF_DIFF=1
 	@cp ${top_srcdir}/doc/manual/R-exts.c .
 	@$(top_builddir)/bin/R CMD SHLIB R-exts.c
 	@$(MAKE) R-exts.Rout
 	@rm R-exts.*
 
 test-Demo:
-	@$(ECHO) "running demos from base and stats"
+	@echo "running demos from base and stats"
 	@$(MAKE) $(test-out-demo) RVAL_IF_DIFF=0
 
 test-Errormsgs:
-	@$(ECHO) "running tests of error messages"
+	@echo "running tests of error messages"
 	@$(MAKE) $(test-out-errmsgs) RVAL_IF_DIFF=0
 
 ## <NOTE>
 ## These depend on an internet connection, and the sites being up.
 ## So allow this to fail: it may be slow doing so.
 test-Internet:
-	@$(ECHO) "running tests of Internet and socket functions"
-	@$(ECHO) "  expect some differences"
+	@echo "running tests of Internet and socket functions"
+	@echo "  expect some differences"
 	-@$(MAKE) $(test-out-internet) RVAL_IF_DIFF=0
 ## </NOTE>
 
 test-IsAs:
-	@$(ECHO) "running tests of consistency of as/is.*"
+	@echo "running tests of consistency of as/is.*"
 	@$(MAKE) $(test-out-isas) RVAL_IF_DIFF=1
 
 test-Primitive:
-	@$(ECHO) "running tests of primitives"
-	@$(MAKE) $(test-out-primitive) RVAL_IF_DIFF=1
+	@echo "running tests of primitives"
+	@$(MAKE) $(test-out-primitive) RVAL_IF_DIFF=0
 
 test-Random:
-	@$(ECHO) "running tests of random deviate generation"
+	@echo "running tests of random deviate generation"
 	@$(MAKE) $(test-out-random) RVAL_IF_DIFF=1
 
 test-Reg:
-	@$(ECHO) "running regression tests"
+	@echo "running regression tests"
 	@$(MAKE) $(test-out-reg) RVAL_IF_DIFF=1
 	@$(MAKE) $(test-out-reg3) RVAL_IF_DIFF=0
 
 test-Regexp:
-	@$(ECHO) "running regexp regression tests"
+	@echo "running regexp regression tests"
 	@$(R2) < $(srcdir)/utf8-regex.R > utf8-regex.Rout 2>&1 || (mv utf8-regex.Rout utf8-regex.Rout.fail && exit 1)
 
 test-Segfault:
-	@$(ECHO) "running tests to possibly trigger segfaults"
+	@echo "running tests to possibly trigger segfaults"
 	@$(MAKE) $(test-out-segfault) RVAL_IF_DIFF=0
 	@rm -f data dumpdata.R F.Rd c0.Rd df0.Rd l0.Rd m0.Rd Rprof.out Rplots.*
 
@@ -293,12 +293,12 @@ test-Segfault:
 ## Not all platforms can build standalone.
 ## So allow this to fail.
 test-Standalone:
-	@$(ECHO) "testing building standalone Rmath"
+	@echo "testing building standalone Rmath"
 	-@(cd $(top_builddir)/src/nmath/standalone; $(MAKE) check)
 ## </NOTE>
 
 test-Rd: $(srcdir)/testit.Rd
-	@$(ECHO) "testing Rd conversion"
+	@echo "testing Rd conversion"
 	@$(RDCONV) -t txt $(srcdir)/testit.Rd > testit.txt
 	@diff -bw testit.txt $(srcdir)/testit.txt.save
 	@$(RDCONV) -t html $(srcdir)/testit.Rd > testit.html
@@ -309,95 +309,95 @@ test-Rd: $(srcdir)/testit.Rd
 	@diff -bw testit-Ex.R $(srcdir)/testit-Ex.R.save
 
 test-DocFiles:
-	@$(ECHO) "checking Rd usage sections"
+	@echo "checking Rd usage sections"
 	@for p in $(R_PKGS_BASE); do \
-	  $(ECHO) $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
-	  out=`($(ECHO) "library(\"tools\")"; \
-	         $(ECHO) "checkDocFiles(package = \"$${p}\")") | \
+	  echo $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
+	  out=`(echo "library(\"tools\")"; \
+	         echo "checkDocFiles(package = \"$${p}\")") | \
 	       $(R) -q | sed '/^>/d'`; \
 	  if test -n "$${out}"; then \
-	    $(ECHO) "$(ECHO_T) WARNING"; \
-	    $(ECHO); \
-	    $(ECHO) "$${out}"; \
-	    $(ECHO); \
+	    echo "$(ECHO_T) WARNING"; \
+	    echo; \
+	    echo "$${out}"; \
+	    echo; \
 	  else \
-	    $(ECHO) "$(ECHO_T) OK"; \
+	    echo "$(ECHO_T) OK"; \
 	  fi; \
 	done
 test-DocStyle:
-	@$(ECHO) "checking S3 method documentation style"
+	@echo "checking S3 method documentation style"
 	@for p in $(R_PKGS_BASE); do \
-	  $(ECHO) $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
-	  out=`($(ECHO) "library(\"tools\")"; \
-	         $(ECHO) "checkDocStyle(package = \"$${p}\")") | \
+	  echo $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
+	  out=`(echo "library(\"tools\")"; \
+	         echo "checkDocStyle(package = \"$${p}\")") | \
 	       $(R) -q | sed '/^>/d'`; \
 	  if test -n "$${out}"; then \
-	    $(ECHO) "$(ECHO_T) WARNING"; \
-	    $(ECHO); \
-	    $(ECHO) "$${out}"; \
-	    $(ECHO); \
+	    echo "$(ECHO_T) WARNING"; \
+	    echo; \
+	    echo "$${out}"; \
+	    echo; \
 	  else \
-	    $(ECHO) "$(ECHO_T) OK"; \
+	    echo "$(ECHO_T) OK"; \
 	  fi; \
 	done
 test-FF:
-	@$(ECHO) "checking foreign function calls"
+	@echo "checking foreign function calls"
 	@for p in $(R_PKGS_BASE); do \
-	  $(ECHO) $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
-	  out=`($(ECHO) "library(\"tools\")"; \
-	         $(ECHO) "checkFF(package = \"$${p}\")") | \
+	  echo $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
+	  out=`(echo "library(\"tools\")"; \
+	         echo "checkFF(package = \"$${p}\")") | \
 	       $(R) -q | sed '/^>/d'`; \
 	  if test -n "$${out}"; then \
-	    $(ECHO) "$(ECHO_T) WARNING"; \
-	    $(ECHO) "$${out}"; \
+	    echo "$(ECHO_T) WARNING"; \
+	    echo "$${out}"; \
 	  else \
-	    $(ECHO) "$(ECHO_T) OK"; \
+	    echo "$(ECHO_T) OK"; \
 	  fi; \
 	done
 test-S3methods:
-	@$(ECHO) "checking for S3 generic/method consistency"
+	@echo "checking for S3 generic/method consistency"
 	@for p in $(R_PKGS_BASE); do \
-	  $(ECHO) $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
-	  out=`($(ECHO) "library(\"tools\")"; \
-	         $(ECHO) "checkS3methods(package = \"$${p}\")") | \
+	  echo $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
+	  out=`(echo "library(\"tools\")"; \
+	         echo "checkS3methods(package = \"$${p}\")") | \
 	       $(R) -q | sed '/^>/d'`; \
 	  if test -n "$${out}"; then \
-	    $(ECHO) "$(ECHO_T) WARNING"; \
-	    $(ECHO); \
-	    $(ECHO) "$${out}"; \
-	    $(ECHO); \
+	    echo "$(ECHO_T) WARNING"; \
+	    echo; \
+	    echo "$${out}"; \
+	    echo; \
 	  else \
-	    $(ECHO) "$(ECHO_T) OK"; \
+	    echo "$(ECHO_T) OK"; \
 	  fi; \
 	done
 test-codoc:
-	@$(ECHO) "checking for code/documentation mismatches in functions"
+	@echo "checking for code/documentation mismatches in functions"
 	@for p in $(R_PKGS_BASE); do \
-	  $(ECHO) $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
-	  out=`($(ECHO) "library(\"tools\")"; \
-	         $(ECHO) "codoc(package = \"$${p}\")") | \
+	  echo $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
+	  out=`(echo "library(\"tools\")"; \
+	         echo "codoc(package = \"$${p}\")") | \
 	       $(R) -q | sed '/^>/d'`; \
 	  if test -n "$${out}"; then \
-	    $(ECHO) "$(ECHO_T) WARNING"; \
-	    $(ECHO); \
-	    $(ECHO) "$${out}"; \
-	    $(ECHO); \
+	    echo "$(ECHO_T) WARNING"; \
+	    echo; \
+	    echo "$${out}"; \
+	    echo; \
 	  else \
-	    $(ECHO) "$(ECHO_T) OK"; \
+	    echo "$(ECHO_T) OK"; \
 	  fi; \
 	done
 test-undoc:
-	@$(ECHO) "checking for missing documentation entries"
+	@echo "checking for missing documentation entries"
 	@for p in $(R_PKGS_BASE); do \
-	  $(ECHO) $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
-	  out=`($(ECHO) "library(\"tools\")"; \
-	         $(ECHO) "undoc(package = \"$${p}\")") | \
+	  echo $(ECHO_N) "package '$${p}' ...$(ECHO_C)"; \
+	  out=`(echo "library(\"tools\")"; \
+	         echo "undoc(package = \"$${p}\")") | \
 	       $(R) -q | sed '/^>/d'`; \
 	  if test -n "$${out}"; then \
-	    $(ECHO) "$(ECHO_T) WARNING"; \
-	    $(ECHO) "$${out}"; \
+	    echo "$(ECHO_T) WARNING"; \
+	    echo "$${out}"; \
 	  else \
-	    $(ECHO) "$(ECHO_T) OK"; \
+	    echo "$(ECHO_T) OK"; \
 	  fi; \
 	done
 
@@ -408,13 +408,13 @@ test-Packages-Recommended:
 	    (cd Packages && $(TAR) xf -) ; \
 	  if grep "^Contains:" "Packages/$${p}/DESCRIPTION" >/dev/null; \
 	  then \
-	    $(ECHO) "checking bundle '$${p}'"; \
+	    echo "checking bundle '$${p}'"; \
 	  else \
-	    $(ECHO) "checking package '$${p}'"; \
+	    echo "checking package '$${p}'"; \
 	  fi; \
 	  R_LIBS="$(top_builddir)/library:$${R_LIBS}" \
             $(top_builddir)/bin/R CMD check --install=skip \
-	    --library="$(top_builddir)/library" Packages/$${p} || $(ECHO); \
+	    --library="$(top_builddir)/library" Packages/$${p} || echo; \
 	done
 
 mostlyclean: clean
